src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Partner_Id__c</fullName>
        <displayFormat>TFP-{0000000}</displayFormat>
        <label>Partner Id</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>loan__Payment_Mode__c</fullName>
        <description>Payment mode, used to disburse payments back to broker.</description>
        <inlineHelpText>Payment mode, used to disburse payments back to broker.</inlineHelpText>
        <label>Payment Mode</label>
        <picklist>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/loan__Loan_Account__c.object
<CustomObject>
    <description>Lending Account</description>
    <fields>
        <fullName>Available_Credit__c</fullName>
        <formula>If(loan__Credit_Limit_Current__c != null,(loan__Credit_Limit_Current__c -  loan__Principal_Remaining__c),( loan__Credit_Limit__c -  loan__Principal_Remaining__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Available Credit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fraudulent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fraudulent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CL Contracts (Partner)</relationshipLabel>
        <relationshipName>CL_Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Borrower_ACH__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Borrower ACH</description>
        <inlineHelpText>Borrower ACH</inlineHelpText>
        <label>Borrower ACH</label>
        <referenceTo>loan__Bank_Account__c</referenceTo>
        <relationshipName>Lending</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Please choose a contact, which will be associated as a customer on this lending account. 
You can create a new contact, from the lookup window by clicking on new or select the existing contact from the lookup.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Loan_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Credit_Limit__c</fullName>
        <description>Credit Limit for Line of Credit</description>
        <inlineHelpText>This is the contractual maximum advance limit, total advance withdrawn must not exceed this limit.</inlineHelpText>
        <label>Credit Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Disbursal_Date__c</fullName>
        <description>Contract Date on the Loan account, this will be updated at the time of funding with the Expected Disbursal Date.</description>
        <inlineHelpText>Contract date on the loan. This will be updated at the time of funding with the expected disbursal date.</inlineHelpText>
        <label>Contract Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>loan__Loan_Status__c</fullName>
        <inlineHelpText>Status of the Account, expected values are :
Pending Approval
Active - Good Standing
Active - Bad Standing
Active - Matured
Approved
Canceled
Closed - Obligations met
Closed- Written Off
Closed - Refinanced
Partial Application</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Partial Application</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active - Good Standing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active - Bad Standing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Obligations met</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed- Written Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Refinanced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active - Matured</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>loan__Minimum_Due_Amount_On_Billing__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Minimum Bill Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Next_Installment_Date__c</fullName>
        <description>Date of the next installment</description>
        <inlineHelpText>Date of the Next Due</inlineHelpText>
        <label>Next Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>loan__Pay_Off_Amount_As_Of_Today__c</fullName>
        <defaultValue>0.0</defaultValue>
        <description>Tells the pay off amount for this account as of today</description>
        <inlineHelpText>Tells the pay off amount for this account as of today</inlineHelpText>
        <label>Today&apos;s Payoff</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Principal_Remaining__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Principal/Advance Remaining</description>
        <inlineHelpText>Unpaid Principal/advance balance on the loan account.</inlineHelpText>
        <label>Principal/Advance Remaining</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Total_Amount_Remaining__c</fullName>
        <description>This field is deprecated and is not maintained.</description>
        <formula>loan__Principal_Remaining__c +  loan__Interest_Accrued_Not_Due__c + loan__Fees_Remaining__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>This field is deprecated and is not maintained.</inlineHelpText>
        <label>Total Amount Remaining</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_Disbursal_Transaction__c.object
<CustomObject>
    <description>This is the final stage where all the documents submitted by a customer are finally checked and the loan is approved.</description>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Loan Disbursal Transactions</relationshipLabel>
        <relationshipName>Loan_Disbursal_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Cleared__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cleared</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>loan__Disbursal_Date__c</fullName>
        <defaultValue>$User.loan__Current_Branch_s_System_Date__c</defaultValue>
        <description>By default, this is the date specified in the proposed disbursal date in the account details. If the date is modified during loan disbursal, the repayment schedule is regenerated accordingly.</description>
        <inlineHelpText>By default, this is the date specified in the proposed disbursal date in the account details. If the date is modified during loan disbursal, the repayment schedule is regenerated accordingly.</inlineHelpText>
        <label>Disbursal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>loan__Disbursed_Amt__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Disbursal Transaction Amount</description>
        <inlineHelpText>Disbursal Transaction Amount</inlineHelpText>
        <label>Disbursal Transaction Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Loan_Account__c</fullName>
        <description>Loan Account</description>
        <inlineHelpText>Loan Account</inlineHelpText>
        <label>Loan Account</label>
        <referenceTo>loan__Loan_Account__c</referenceTo>
        <relationshipLabel>Loan Disbursal Transactions</relationshipLabel>
        <relationshipName>Loan_Disbursal_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>loan__Mode_of_Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mode of Payment</label>
        <referenceTo>loan__Payment_Mode__c</referenceTo>
        <relationshipLabel>Loan Disbursal Transactions</relationshipLabel>
        <relationshipName>Loan_Disbursal_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Reference__c</fullName>
        <label>Reference</label>
        <length>64</length>
        <type>Text</type>
    </fields>
    <label>Loan Disbursal Transaction</label>
    <nameField>
        <displayFormat>LDTI-{0000000000}</displayFormat>
        <label>Loan Disbursal Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Disbursal Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/loan__Loan_Payment_Transaction__c.object
<CustomObject>
    <description>Loan Payment Transaction</description>
    <fields>
        <fullName>loan__Cleared__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if this loan payment transaction is supervised or not.</description>
        <inlineHelpText>Indicates if this loan payment transaction is supervised or not.</inlineHelpText>
        <label>Cleared</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>loan__Dependent_Payment_Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dependent Payment Transaction</label>
        <referenceTo>loan__Loan_Payment_Transaction__c</referenceTo>
        <relationshipLabel>Loan Payment Transactions</relationshipLabel>
        <relationshipName>Loan_Payment_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Loan_Account__c</fullName>
        <description>Loan Account</description>
        <inlineHelpText>Loan Account</inlineHelpText>
        <label>Loan Account</label>
        <referenceTo>loan__Loan_Account__c</referenceTo>
        <relationshipLabel>Loan Payment Transactions</relationshipLabel>
        <relationshipName>Loan_Payment_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>loan__Payment_Mode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Mode</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>loan__Payment_Mode__c.Name</field>
                <operation>notEqual</operation>
                <value>Internal Transfer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>loan__Payment_Mode__c</referenceTo>
        <relationshipLabel>Loan Payment Transactions</relationshipLabel>
        <relationshipName>Loan_Payment_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Transaction_Amount__c</fullName>
        <description>Transaction Amount</description>
        <inlineHelpText>This is the sum of Interest, Principal and Fees</inlineHelpText>
        <label>Transaction Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Transaction_Date__c</fullName>
        <defaultValue>$User.loan__Current_Branch_s_System_Date__c</defaultValue>
        <description>Transaction Date</description>
        <inlineHelpText>Transaction Date</inlineHelpText>
        <label>Transaction Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>loan__Transaction_Time__c</fullName>
        <label>Transaction Time</label>
        <type>DateTime</type>
    </fields>
    <label>Loan Payment Transaction</label>
    <nameField>
        <displayFormat>LPT-{000000000}</displayFormat>
        <label>Loan Payment Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Payment Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/loan__Loan_Status__c.object
<CustomObject>
    <description>Object for storing Loan Statuses</description>
    <label>Loan Status</label>
    <nameField>
        <label>Loan Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Payment_Mode__c.object
<CustomObject>
    <label>Payment Mode</label>
    <nameField>
        <label>Payment Mode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Mode</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WSAccountDetails.cls
@RestResource(urlMapping='/v1/accountDetails')
global with sharing class WSAccountDetails {
    
    @HttpPost
    global static Response getAccountDetails() {
        RestRequest req = RestContext.request;
        RestResponse restRes = RestContext.response;
        Response res = new Response();
        
        System.debug(LoggingLEvel.ERROR,' Request Received '+req);
        
        RequestBodyParser.RequestBodyParams reqParams = RequestBodyParser.getJsonParamsFromRequest(req);
        
        if(reqParams == null) {
            
            res.errorCode = peer.Constants.INVALID_INPUT;
            res.status = peer.Constants.ERROR;
            res.errorMessage = 'Unable to parse request';
            restRes.statuscode = peer.Constants.HTTP_BAD_REQUEST;
            return res;
        }
        
        Map<String, Object> params = reqParams.getParams();
        String username = null;
        
        loan.GlobalLoanUtilFacade f = new loan.GlobalLoanUtilFacade();
        Date systemDate = f.getCurrentSystemDate();
        
        try {
            if (params.get('username') != null) {
                username = (String)params.get('username');
            }
        }catch(Exception e) {
            res.errorCode = peer.Constants.INVALID_INPUT;
            res.status = peer.Constants.ERROR;
            res.errorMessage = 'Error while parsing request parameters.';
            restRes.statuscode = peer.Constants.HTTP_BAD_REQUEST;
            return res;
        }

        if(username == null){
            res.errorCode = peer.Constants.INVALID_INPUT;
            res.status = peer.Constants.ERROR;
            res.errorMessage = 'Username can not be null';
            restRes.statuscode = peer.Constants.HTTP_BAD_REQUEST;
            return res;
        } 
        
        //Fetch Contact.
        List<Contact> bList = [Select Id,Name from Contact Where Id =: username];
        
        if(bList.isEmpty()){
            res.errorCode = peer.Constants.INVALID_INPUT;
            res.status = peer.Constants.ERROR;
            res.errorMessage = 'No user found for given username';
            restRes.statuscode = peer.Constants.HTTP_BAD_REQUEST;
            return res;
        }
        
        if(bList.size() > 1){
            res.errorCode = peer.Constants.INVALID_INPUT;
            res.status = peer.Constants.ERROR;
            res.errorMessage = 'More than one users found for given username. Please contact support.';
            restRes.statuscode = peer.Constants.HTTP_BAD_REQUEST;
            return res;
        }
                
        Contact borrower = bList[0];
        
        Set<String> notAllowedStatus = new Set<String>();
        notAllowedStatus.add(loan.LoanConstants.LOAN_STATUS_PARTIAL_APPLICATION);
        notAllowedStatus.add(loan.LoanConstants.LOAN_STATUS_PENDING_APPROVAL);
        notAllowedStatus.add(loan.LoanConstants.LOAN_STATUS_CLOSED_OBLIGATIONS_MET);
        
        //Fetch Contract
        List<loan__Loan_Account__c> locContracts = [Select Id,Name,
                                                           loan__Contact__c,
                                                           loan__Contact__r.Name,
                                                           loan__Contact__r.Email,
                                                           loan__Credit_Limit__c,
                                                           Fraudulent__c,
                                                           loan__Total_Amount_Remaining__c,
                                                           loan__Pay_Off_Amount_As_Of_Today__c,
                                                           loan__Borrower_ACH__c,
                                                           loan__Principal_Remaining__c,
                                                           loan__Minimum_Due_Amount_On_Billing__c,
                                                           loan__Next_Installment_Date__c,
                                                           Available_Credit__c,
                                                           //Loan Payment Transactions.
                                                           (Select Id,Name,
                                                                   loan__Transaction_Amount__c,
                                                                   loan__Transaction_Date__c,
                                                                   loan__Payment_Mode__C,
                                                                   loan__Cleared__c
                                                            From loan__Loan_Payment_Transactions__r
                                                            Order by loan__Transaction_time__c DESC),
                                                            //Loan Disbursement Transactions.
                                                            (Select Id,Name,
                                                                    loan__Disbursed_Amt__c,
                                                                    loan__Disbursal_Date__c,
                                                                    loan__Reference__c,
                                                                    Partner__r.Partner_Id__c
                                                             From loan__Loan_Disbursal_Transactions__r
                                                             Order by loan__Disbursal_Date__c DESC)
                                                    From loan__Loan_Account__c
                                                    Where loan__Contact__c =: borrower.Id
                                                    and loan__Contact__c != null
                                                    and loan__Loan_Status__c NOT IN: notAllowedStatus];
        
        if (locContracts.isEmpty()) {
            res.errorCode = 'CONTRACT_NOT_FOUND';
            res.status = peer.Constants.ERROR;
            res.errorMessage = 'LOC Contract not found for given Username';
            restRes.statuscode = peer.Constants.HTTP_BAD_REQUEST;
            return res;

        } 
                
        try {
            for(loan__Loan_Account__c loan : locContracts){
                res.content.add(loan);
            }
        } catch(Exception e) {
            
            res.errorCode = peer.Constants.API_EXCEPTION;
            res.errorMessage = e.getMessage()+' From line '+e.getLineNumber();
            res.status = peer.Constants.ERROR;
            restRes.statuscode = peer.Constants.HTTP_INTERNAL_ERROR;
            return res;  
        }
                             
        //res.content.add(vCard);
        res.status = peer.Constants.SUCCESS;
        restRes.statuscode = peer.Constants.HTTP_OK;
        return res;
    }
    
}