src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Partner_Id__c</fullName>
        <displayFormat>TFP-{0000000}</displayFormat>
        <label>Partner Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>loan__Broker__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Tick, if the Account is a Broker.</inlineHelpText>
        <label>Broker</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>loan__Payment_Mode__c</fullName>
        <description>Payment mode, used to disburse payments back to broker.</description>
        <inlineHelpText>Payment mode, used to disburse payments back to broker.</inlineHelpText>
        <label>Payment Mode</label>
        <picklist>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/loan__Automated_Payment_Setup__c.object
<CustomObject>
    <fields>
        <fullName>loan__Payment_Mode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Mode</label>
        <referenceTo>loan__Payment_Mode__c</referenceTo>
        <relationshipName>ACH_Setup</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Automated Payment Setup</label>
    <nameField>
        <displayFormat>APS-{0000000000}</displayFormat>
        <label>Automated Payment Setup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Automated Payment Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Broker__c.object
<CustomObject>
    <fields>
        <fullName>loan__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Broker Contact for this lending account.</description>
        <inlineHelpText>Broker Contact for this lending account.</inlineHelpText>
        <label>Broker Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.loan__Contact_Type__c</field>
                <operation>equals</operation>
                <value>Broker</value>
            </filterItems>
            <infoMessage>Please select the appropriate broker</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Brokers</relationshipLabel>
        <relationshipName>Brokers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Broker</label>
    <nameField>
        <displayFormat>LB-{000000000}</displayFormat>
        <label>Broker Record Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brokers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/loan__Loan_Account__c.object
<CustomObject>
    <description>Lending Account</description>
    <fields>
        <fullName>Contract_Originated_From__c</fullName>
        <label>Contract Originated From</label>
        <picklist>
            <picklistValues>
                <fullName>Organic Acquisition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Party Referrer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>loan__Balloon_Payment__c</fullName>
        <inlineHelpText>Heavy payment at the end of a loan payment schedule.</inlineHelpText>
        <label>Balloon Payment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Borrower_ACH__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Borrower ACH</description>
        <inlineHelpText>Borrower ACH</inlineHelpText>
        <label>Borrower ACH</label>
        <referenceTo>loan__Bank_Account__c</referenceTo>
        <relationshipName>Lending</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Please choose a contact, which will be associated as a customer on this lending account. 
You can create a new contact, from the lookup window by clicking on new or select the existing contact from the lookup.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Loan_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Contractual_Interest_Rate__c</fullName>
        <inlineHelpText>Contractual Interest Rate on the contract.</inlineHelpText>
        <label>Interest Rate</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Credit_Limit__c</fullName>
        <description>Credit Limit for Line of Credit</description>
        <inlineHelpText>This is the contractual maximum advance limit, total advance withdrawn must not exceed this limit.</inlineHelpText>
        <label>Credit Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Expected_Disbursal_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <inlineHelpText>This is the expected date on which the loan will be disbursed to the customer, this date will be used to derive the contract date.</inlineHelpText>
        <label>Expected Disbursal Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>loan__Expected_Repayment_Start_Date__c</fullName>
        <defaultValue>TODAY() + 30</defaultValue>
        <inlineHelpText>This will be the date from when the customer will be start making the payments on this contract. The first payment date will be derived from payment start date.</inlineHelpText>
        <label>Payment Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>loan__First_Installment_Date__c</fullName>
        <description>Date of the first installment</description>
        <inlineHelpText>This is the desired start date of the repayment schedule that is provided while creating the loan application.</inlineHelpText>
        <label>First Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>loan__Frequency_of_Loan_Payment__c</fullName>
        <inlineHelpText>This decides the Payment Frequency, below are the supported ones:
Daily
Weekly
Bi-weekly
Semi-Monthly
Monthly
Bi-Monthly  
Quarterly
Semi-Annual
Annual 
Single-Payment</inlineHelpText>
        <label>Payment Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Daily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single-Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Monthly-PD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>loan__Interest_Calculation_Method__c</fullName>
        <description>Billing Method.</description>
        <inlineHelpText>Flat - Interest computed every month on the original amount. 
Declining Balance - Interest calculated on the reduced principal balance.
Flexible Repayment - Interest calculated on the reduced principal balance with the change in interest rate.</inlineHelpText>
        <label>Interest Calculation Method</label>
        <picklist>
            <picklistValues>
                <fullName>Flat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declining Balance</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Flexible Repayment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>loan__Loan_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Loan Amount</description>
        <inlineHelpText>This is the financed amount on the contract which will be disbursed to the customer.</inlineHelpText>
        <label>Loan Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Next_Installment_Date__c</fullName>
        <description>Date of the next installment</description>
        <inlineHelpText>Date of the Next Due</inlineHelpText>
        <label>Next Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>loan__Number_of_Installments__c</fullName>
        <description>Contractual Term Of the Loan Account</description>
        <inlineHelpText>Contractual term of the contract.</inlineHelpText>
        <label>Term</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Second_Installment_Date__c</fullName>
        <description>Date of the Second installment</description>
        <inlineHelpText>This is the second Payment Date and will be used only for semi monthly Payday loans.</inlineHelpText>
        <label>Second Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>loan__Term_Cur__c</fullName>
        <description>Current Term</description>
        <inlineHelpText>Current loan account term.</inlineHelpText>
        <label>Current Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Time_Counting_Method__c</fullName>
        <inlineHelpText>Time Counting Method :
1) Month and Days will use 360 days in a year for the Interest calculation.
2) Actual Days will use 365 days in a year for the Interest calculation.</inlineHelpText>
        <label>Time Counting Method</label>
        <picklist>
            <picklistValues>
                <fullName>Month And Days</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Actual Days</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_Disbursal_Transaction__c.object
<CustomObject>
    <description>This is the final stage where all the documents submitted by a customer are finally checked and the loan is approved.</description>
    <fields>
        <fullName>loan__Loan_Account__c</fullName>
        <description>Loan Account</description>
        <inlineHelpText>Loan Account</inlineHelpText>
        <label>Loan Account</label>
        <referenceTo>loan__Loan_Account__c</referenceTo>
        <relationshipLabel>Loan Disbursal Transactions</relationshipLabel>
        <relationshipName>Loan_Disbursal_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Loan Disbursal Transaction</label>
    <nameField>
        <displayFormat>LDTI-{0000000000}</displayFormat>
        <label>Loan Disbursal Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Disbursal Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/loan_ix__Ixaris_logins__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>loan_ix__Currency__c</fullName>
        <label>Currency</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Ixaris logins</label>
</CustomObject>

src/objects/Virtual_Card__c.object
<CustomObject>
    <fields>
        <fullName>Loan_Account__c</fullName>
        <label>CL Contract</label>
        <referenceTo>loan__Loan_Account__c</referenceTo>
        <relationshipLabel>Virtual Cards</relationshipLabel>
        <relationshipName>Virtual_Cards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Loan_Disbursal_Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan Disbursal Transaction</label>
        <referenceTo>loan__Loan_Disbursal_Transaction__c</referenceTo>
        <relationshipLabel>Virtual Cards</relationshipLabel>
        <relationshipName>Virtual_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Virtual Card</label>
    <nameField>
        <label>Virtual Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Virtual Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/WSVirtualCard_v1.cls
@RestResource(urlMapping='/v1/virtualCard')
global class WSVirtualCard_v1 {

    global class VirtualCardResponse extends Response {
         global VirtualCard card {get;set;}
           
         public VirtualCardResponse() {
             card = new VirtualCard();
         }
    }
    
    @HttpPost
    global static Response createVirtualCard() {
        RestRequest req = RestContext.request;
        RestResponse restRes = RestContext.response;
        VirtualCardResponse res = new VirtualCardResponse();
        
        System.debug(LoggingLEvel.ERROR,' Request Received '+req);
        
        RequestBodyParser.RequestBodyParams reqParams = RequestBodyParser.getJsonParamsFromRequest(req);
        if(reqParams == null) {
            
            res.errorCode = peer.Constants.INVALID_INPUT;
            res.status = peer.Constants.ERROR;
            res.errorMessage = 'Unable to parse request';
            restRes.statuscode = peer.Constants.HTTP_BAD_REQUEST;
            return res;
        }
        
        Map<String, Object> params = reqParams.getParams();
        String contractId = null;
        Decimal amount = null;
        Date systemDate;
        String merchantReference;
        String partnerId;
        Account partner;
        
        loan.GlobalLoanUtilFacade f = new loan.GlobalLoanUtilFacade();
        systemDate = f.getCurrentSystemDate();
        
        try {
            if (params.get('contractId') != null) {
                contractId = (String)params.get('contractId');
            }
            if(params.get('amount') != null) {
                amount = (Decimal)params.get('amount');
            }
            
            if(params.get('partnerId') != null) {
                merchantReference = (String)params.get('partnerId');
            }
        }catch(Exception e) {
            res.errorCode = peer.Constants.INVALID_INPUT;
            res.status = peer.Constants.ERROR;
            res.errorMessage = 'Error while parsing request parameters.';
            restRes.statuscode = peer.Constants.HTTP_BAD_REQUEST;
            return res;
        }

        if(contractId == null){
            res.errorCode = peer.Constants.INVALID_INPUT;
            res.status = peer.Constants.ERROR;
            res.errorMessage = 'ContractId can not be null';
            restRes.statuscode = peer.Constants.HTTP_BAD_REQUEST;
            return res;
        } 
        
        if(amount == null) {
            res.errorCode = peer.Constants.INVALID_INPUT;
            res.status = peer.Constants.ERROR;
            res.errorMessage = 'Amount can not be null';
            restRes.statuscode = peer.Constants.HTTP_BAD_REQUEST;
            return res;
        }
        
        //Fetch Merchant
        List<Account> partners = [Select Id,Name,
                                         partner_Id__c,
                                         loan__Broker__c
                                  From Account
                                  Where Partner_Id__c =: merchantReference];
                                  
        if(!partners.isEmpty()){                          
            partnerId = partners[0].Id;  
            partner = partners[0];                        
        }
        
        //Fetch Contract
        List<loan__Loan_Account__c> locContracts = [Select Id,Name,
                                                           loan__Contact__c,
                                                           loan__Contact__r.Name,
                                                           loan__Contact__r.FirstName,
                                                           loan__Contact__r.LastName,
                                                           loan__Contact__r.Email,
                                                           loan__Loan_Amount__c,
                                                           loan__Credit_Limit__c,
                                                           loan__Borrower_ACH__c,
                                                           loan__Contractual_Interest_Rate__c,
                                                           loan__Expected_Disbursal_Date__c,
                                                           loan__Expected_Repayment_Start_Date__c,
                                                           loan__Number_of_Installments__c,
                                                           loan__Time_Counting_Method__c,
                                                           loan__Balloon_Payment__c,
                                                           loan__Frequency_of_Loan_Payment__c,
                                                           loan__Interest_Calculation_Method__c,
                                                           loan__First_Installment_Date__c,
                                                           loan__Second_Installment_Date__c,
                                                           loan__Next_Installment_Date__c,
                                                           Contract_Originated_From__c,
                                                           loan__Term_Cur__c
                                                    From loan__Loan_Account__c
                                                    Where Id =: contractId];
        
        if (locContracts.isEmpty()) {
            res.errorCode = 'CONTRACT_NOT_FOUND';
            res.status = peer.Constants.ERROR;
            res.errorMessage = 'LOC Contract not found for given ID';
            restRes.statuscode = peer.Constants.HTTP_BAD_REQUEST;
            return res;

        } 
        
        //Create Virtual Card
        Virtual_Card__c vCard;
        loan_ix.VirtualCard newCard;
        loan__Payment_Mode__c pMode;
        loan__Loan_Disbursal_Transaction__c dTxn;
        
        try {
            
            //Get API instance
            loan_ix.CardAPI api = loan_ix.FactoryFacade.getAPI();
            
            //get Custom Setting Details    
            loan_ix__Ixaris_Logins__c lDetails = loan_ix__Ixaris_Logins__c.getOrgDefaults();  
            
            String accessToken = api.login(false);    
            
            String custName = locContracts[0].loan__Contact__r.FirstName + ' ' +
                              locContracts[0].loan__Contact__r.LastName + ' # ' +
                              System.now();
            
            System.debug(LoggingLevel.ERROR,' accessToken '+accessToken);
            System.debug(LoggingLevel.ERROR,' accessToken '+custName);
            System.debug(LoggingLevel.ERROR,' accessToken '+lDetails.loan_ix__Currency__c);
            System.debug(LoggingLevel.ERROR,' accessToken '+amount+' '+lDetails.loan_ix__Card_Factory__c);
                                       
                                       
            //Create Virtual Card 
            newCard = api.issueVirtualCard(accessToken,custName,lDetails.loan_ix__Currency__c,
                                                               lDetails.Funding_Account_Reference__C,
                                                               amount,
                                                               lDetails.loan_ix__Card_Factory__c,'');
                                                                                        
            
            if(newCard == null){
                throw new GeneralException('Error while creating Virtual Card');
            }
            
            newCard = api.getVirtualCardDetails(accessToken,newCard.cardReference);
             
            //Loan Disbursement.
            BorrowerImpl b = new BorrowerImpl();
            dTxn = b.disburseLocAccount(systemDate,amount,
                                        locContracts[0],partnerId,
                                        lDetails.Funding_Account_Reference__C);
            
            dTxn = [Select Id,Disbursal_Transaction_Id__c,
                           Partner__c,
                           loan__Loan_Account__c
                    from loan__Loan_Disbursal_Transaction__c Where Id =: dTxn.Id];
            
            //Create Virtual Card Record.
            vCard = new Virtual_Card__c();
            vCard.Name = newCard.cardName;
            vCard.Loan_Account__c = locContracts[0].Id;
            vCard.Card_Reference__c = newCard.cardReference;
            vCard.Partner__c = partnerId;
            vCard.Loan_Disbursal_Transaction__c = dTxn.Id;
            insert vCard;
            
            //Setup Brokerage
            if(locContracts[0].Contract_Originated_From__c.equalsIgnoreCase('Organic Acquisition')) {
                List<loan__Commission_Plan__c> bPlan = b.getCommissionPlans();
                loan__Broker__c newBroker = b.setupBrokeragePlan(locContracts[0],partner,bPlan[0]);
            }
            
            //Setup Recurring ACH.
            pMode = [Select Id,Name from loan__Payment_Mode__c Where Name = 'ACH'];
            
            if(!isAchAlreadySetup(locContracts[0])) {
                b.setUpACHonContract(locContracts[0],date.today(),'Monthly','Recurring',pMode);
            }
            
        } catch(Exception e) {
            res.errorCode = peer.Constants.API_EXCEPTION;
            res.errorMessage = e.getMessage()+' From line '+e.getLineNumber();
            res.status = peer.Constants.ERROR;
            restRes.statuscode = peer.Constants.HTTP_INTERNAL_ERROR;
            return res;  
        }
                             
        res.content.add(dTxn);
        res.card = getVirtualCardforResponse(newCard);
        res.status = peer.Constants.SUCCESS;
        restRes.statuscode = peer.Constants.HTTP_OK;
        return res;
    }
    
    private static boolean isAchAlreadySetup(loan__Loan_Account__c loanAcc) {
        
        List<loan__Automated_Payment_setup__c> achSetup = [Select Id,Name from loan__Automated_Payment_Setup__c 
                                                           Where loan__Active__c = true 
                                                           and loan__CL_Contract__c =: loanAcc.Id];
    
        if(achSetup.isEmpty()){
            return false;
        }else{
            return true;
        }
    }
    
    private static VirtualCard getVirtualCardforResponse(loan_ix.VirtualCard card) {
        VirtualCard retVal = new VirtualCard();
        
        retVal.cardName = card.cardName;
        retVal.state = card.state;
        retVal.cardBrand = card.cardBrand;
        retVal.cardNumber = card.cardNumber;
        retVal.cardholderName = card.cardholderName;
        retVal.availableBalance = card.availableBalance;
        retVal.actualBalance = card.actualBalance;
        retVal.cvv = card.cvv;
        retVal.expiryDateMonth = card.expiryDateMonth;
        retVal.expiryDateYear = card.expiryDateYear;
        retVal.expiryPeriod = card.expiryPeriod;
        retVal.nameOnCard = card.nameOnCard;
        retVal.startDateMonth = card.startDateMonth;
        retVal.startDateYear = card.startDateYear;
        retVal.isDefault = card.isDefault;
        retVal.cardReference = card.cardReference;
        retVal.cardType = card.cardType;
        retVal.externalIdentifier = card.externalIdentifier;
        retVal.cardInfo = card.cardInfo;
        retVal.orderedCardInfo = card.orderedCardInfo;
        retVal.transactionReference = card.transactionReference;
        
        return retVal;
    }
}