src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>loan__Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Bank_Account__c.object
<CustomObject>
    <fields>
        <fullName>Bank_Card_Details__c</fullName>
        <label>Card Number</label>
        <length>20</length>
        <maskChar>X</maskChar>
        <maskType>creditCard</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>CVV__c</fullName>
        <label>Security Code</label>
        <length>3</length>
        <maskChar>X</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Expiry_Month__c</fullName>
        <label>Expiry Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expiry_Year__c</fullName>
        <label>Expiry Year</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Account_Type__c</fullName>
        <label>Account Type</label>
        <picklist>
            <picklistValues>
                <fullName>Saving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checking</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>loan__Account_Usage__c</fullName>
        <label>Account Usage</label>
        <picklist>
            <picklistValues>
                <fullName>Investor Trust Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collections Trust Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advance Trust Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tax Withholding Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Borrower/Investor Account</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>loan__Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>loan__Bank_Account_Number__c</fullName>
        <label>Bank Account Number</label>
        <length>50</length>
        <maskChar>X</maskChar>
        <maskType>lastFour</maskType>
        <required>true</required>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>loan__Bank_Name__c</fullName>
        <label>Bank Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>loan__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bank Accounts</relationshipLabel>
        <relationshipName>Bank_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>peer__Allow_for_Direct_Credit__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow for Direct Credit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>peer__Savings_No__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Savings_No</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>peer__Savings_Other__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Savings Other</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>peer__Savings_Pensions__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Savings Pensions</label>
        <type>Checkbox</type>
    </fields>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Bank Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Currency__c.object
<CustomObject>
    <description>Currency</description>
    <label>Currency</label>
    <nameField>
        <label>Currency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Fee__c.object
<CustomObject>
    <description>Fee</description>
    <fields>
        <fullName>loan__Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Currency</description>
        <inlineHelpText>Currency</inlineHelpText>
        <label>Currency</label>
        <referenceTo>loan__Currency__c</referenceTo>
        <relationshipLabel>Fees</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fee</label>
    <nameField>
        <label>Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Fee_Junction__c.object
<CustomObject>
    <fields>
        <fullName>loan__Fee_Set__c</fullName>
        <label>Fee Set</label>
        <referenceTo>loan__Fee_Set__c</referenceTo>
        <relationshipName>Fee_Junction</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>loan__Fee__c</fullName>
        <label>Fee</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>loan__Fee__c.loan__Time_of_charge__c</field>
                <operation>notEqual</operation>
                <value>Pre-Paid Fees</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>loan__Fee__c</referenceTo>
        <relationshipLabel>Fee Set/Fee</relationshipLabel>
        <relationshipName>Fee_Junction</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Fee Set/Fee</label>
    <nameField>
        <displayFormat>FJIP-{0000000000}</displayFormat>
        <label>Fee Junction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fee Set/Fee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/loan__Fee_Set__c.object
<CustomObject>
    <description>A set of fee</description>
    <label>Fee Set</label>
    <nameField>
        <label>Fee Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fee Set</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_Account__c.object
<CustomObject>
    <description>Lending Account</description>
    <fields>
        <fullName>loan__Account_Type__c</fullName>
        <label>Account Type</label>
        <picklist>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Type2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>loan__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Please choose a contact, which will be associated as a customer on this lending account. 
You can create a new contact, from the lookup window by clicking on new or select the existing contact from the lookup.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Loan_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Fee_Set__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Fee Set</description>
        <inlineHelpText>Lookup to associate the fee set on this lending account. Only the fees defined within the fee set can be assessed on this contract.
To create a fee set, Servicing configuration-&gt;Product-&gt;Manage fee set</inlineHelpText>
        <label>Fee Set</label>
        <referenceTo>loan__Fee_Set__c</referenceTo>
        <relationshipName>Loan_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Loan_Purpose__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Loan Purpose</description>
        <inlineHelpText>Loan purpose</inlineHelpText>
        <label>Purpose</label>
        <referenceTo>loan__Loan_Purpose__c</referenceTo>
        <relationshipName>Loan_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Payment_Application_Mode__c</fullName>
        <description>If the value is Future Dues, Reserve Amount For Next Due will be used for satisfying Bills. Otherwise, Reserve Amount For Next Due will not be used for satisfying Bills.</description>
        <inlineHelpText>Possible values are 
1) Future Dues
2) Current Dues
Future Dues is used when Loan Payments should be used to satisfy future dues.
Current Dues is used when Loan Payments should only be used to satisfy present dues.</inlineHelpText>
        <label>Payment Application Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Future Dues</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Current Dues</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_Product__c.object
<CustomObject>
    <description>Lending Product Definition1</description>
    <fields>
        <fullName>loan__Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Currency</description>
        <inlineHelpText>Currency</inlineHelpText>
        <label>Currency</label>
        <referenceTo>loan__Currency__c</referenceTo>
        <relationshipName>Loan_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Fee_Set__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fee Set</description>
        <inlineHelpText>Fee set contains the details of all the fees associated with the loan.</inlineHelpText>
        <label>Fee Set</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected Fee Set&apos;s category must be of type &apos;Loan&apos; and it should include at least one fee.</errorMessage>
            <filterItems>
                <field>loan__Fee_Set__c.loan__Fee_Set_Category__c</field>
                <operation>equals</operation>
                <value>Loan</value>
            </filterItems>
            <filterItems>
                <field>loan__Fee_Set__c.loan__Number_of_Fees__c</field>
                <operation>notEqual</operation>
                <value>0</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>loan__Fee_Set__c</referenceTo>
        <relationshipName>Loan_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Payment_Application_Mode__c</fullName>
        <description>If the value is Future Dues, Reserve Amount For Next Due will be used for satisfying Bills. Otherwise, Reserve Amount For Next Due will not be used for satisfying Bills.</description>
        <inlineHelpText>Select Future Dues if the loan payments must be used to satisfy future dues. 
 Select Current Dues if the loan payments must be used to to satisfy present dues.</inlineHelpText>
        <label>Payment Application Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Future Dues</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Current Dues</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Lending Product</label>
    <nameField>
        <label>Loan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lending Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_Purpose__c.object
<CustomObject>
    <description>Loan Purpose</description>
    <label>Loan Purpose</label>
    <nameField>
        <label>Loan Purpose Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Purpose</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__MF_Account__c.object
<CustomObject>
    <fields>
        <fullName>loan__Account_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account Type</description>
        <inlineHelpText>Account Type</inlineHelpText>
        <label>Account Type</label>
        <referenceTo>loan__MF_Account_Type__c</referenceTo>
        <relationshipName>MF_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GL Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Office_Name__c.object
<CustomObject>
    <description>Name of the office</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_WSLoanPayments.cls
@isTest
public class Test_WSLoanPayments{
         static loan__Loan_Account__c loanAccount;
        public testmethod static void createData(){
            loan.TestHelper.createSeedDataForTesting();
            loan__Currency__c curr                    = loan.TestHelper.createCurrency();
            //Create a dummy MF_Account
            loan__MF_Account__c dummyAccount          = loan.TestHelper.createMFAccount('XXXAccountForTest','10000 - ASSETS');
            loan__MF_Account__c dummyIncAccount       = loan.TestHelper.createMFAccount('XXXIncAccountForTest','30000 - INCOME');
            
            //Create a Fee Set
            loan__Fee__c dummyFee                     = loan.TestHelper.createFee(curr,dummyIncAccount ,dummyAccount);                                    
            loan__Fee_Set__c dummyFeeSet               = loan.TestHelper.createFeeSet();
            loan__Fee_Junction__c dummyFeeJunction     = loan.TestHelper.createFeeJunction(dummyFee,dummyFeeSet);
            
            loan__Office_Name__c dummyOffice          = loan.TestHelper.createOffice();
            
            //Create a dummy Loan Product
            loan__Loan_Product__c dummyLP             = loan.TestHelper.createLoanProduct(dummyOffice,
                                                                                       dummyAccount, 
                                                             curr, 
                                                             dummyFeeSet);
            dummyLP.loan__Payment_Application_Mode__c = loan.LoanConstants.LOAN_PAYMENT_APPLICATION_CURRENT_DUES;
            
            update dummyLP;
            //System.debug(LoggingLevel.ERROR,'LoanProduct in test: ' + dummyLP.Disable_Reserve_Amount_for_Next_Due__c);
            loan__Loan_Purpose__c dummyLoanPurpose     = loan.TestHelper.createLoanPurpose();        
            
            Contact dummyClient = new Contact(LastName = 'Test Contact');
            insert dummyClient;
            
            loan__Bank_Account__c loanAcc = new loan__Bank_Account__c();
            loanAcc.Bank_Card_Details__c    =   'XXXX-XXXX-XXXX-0203' ;
            loanAcc.CVV__c  =   'XXX' ;
            loanAcc.Expiry_Month__c =   9   ;
            loanAcc.Expiry_Year__c  =   17  ;
            loanAcc.loan__Account_Type__c   =   'Savings' ;
            loanAcc.loan__Account_Usage__c  =   'Borrower/Investor Account'   ;
            loanAcc.loan__Active__c =   TRUE   ;
            loanAcc.loan__Bank_Account_Number__c    =   'XXXXXXXXXXXX0203'    ;
            loanAcc.loan__Bank_Name__c  =   'Visa'    ;
            loanAcc.loan__Contact__c    =   dummyClient.Id  ;
            loanAcc.peer__Allow_for_Direct_Credit__c    =   FALSE   ;
            loanAcc.peer__Savings_No__c =   FALSE   ;
            loanAcc.peer__Savings_Other__c  =   FALSE   ;
            loanAcc.peer__Savings_Pensions__c   =   FALSE   ;
            insert loanAcc;
            
            //Create a dummy Loan Account
            loanAccount = loan.TestHelper.createLoanAccountForContactObj(dummyLP,
                                                        dummyClient,
                                                        dummyFeeSet,
                                                        dummyLoanPurpose,
                                                        dummyOffice);
      }
  
  @isTest static void test_method_WSLoanPayments_v1_1() {
        // Implement test code
        createData();
        RestRequest req  = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/v1/payments';
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        Response results = WSLoanPayments.createLoanPayment();
        Test.stopTest();
    }

    @isTest static void test_method_WSLoanPayments_v1_2() {
        // Implement test code
        createData();
        String loanId = loanAccount.Id;
        Map<String,Object> reqBodyMap = new Map<String,Object>();
        reqBodyMap.put('contractId', loanId);
        reqBodyMap.put('cardNumber', '123456');
        reqBodyMap.put('cvv', '123');
        reqBodyMap.put('month', 3);
        reqBodyMap.put('year', 2016);
        reqBodyMap.put('bankName', 'testBANK');
        RestRequest req  = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/v1/payments';
        req.requestBody = Blob.valueOf(JSON.serialize(reqBodyMap));
//        req.(JSON.serializePretty('contractId:'+loanId));
//        req.addParameter('contractId', loanAccount.Id);
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        Response results = WSLoanPayments.createLoanPayment();
        Test.stopTest();
    }

    @isTest static void test_method_WSLoanPayments_v1_3() {
        // Implement test code
        createData();
        String loanId = loanAccount.Id;
        Map<String,Object> reqBodyMap = new Map<String,Object>();
        reqBodyMap.put('contractId', null);
        RestRequest req  = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/v1/payments';
        req.requestBody = Blob.valueOf(JSON.serialize(reqBodyMap));
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        Response results = WSLoanPayments.createLoanPayment();
        Test.stopTest();
    }


    @isTest static void test_method_WSLoanPayments_v1_4() {
        // Implement test code
        createData();
        String loanId = loanAccount.Id;
        Map<String,Object> reqBodyMap = new Map<String,Object>();
        reqBodyMap.put('contractId', loanId);
        reqBodyMap.put('cardNumber', null);
        RestRequest req  = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/v1/payments';
        req.requestBody = Blob.valueOf(JSON.serialize(reqBodyMap));
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        Response results = WSLoanPayments.createLoanPayment();
        Test.stopTest();
    }    

    @isTest static void test_method_WSLoanPayments_v1_5() {
        // Implement test code
        createData();
        String loanId = loanAccount.Id;
        Map<String,Object> reqBodyMap = new Map<String,Object>();
        reqBodyMap.put('contractId', loanId);
        reqBodyMap.put('cardNumber', '1234');
        reqBodyMap.put('cvv', null);
        RestRequest req  = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/v1/payments';
        req.requestBody = Blob.valueOf(JSON.serialize(reqBodyMap));
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        Response results = WSLoanPayments.createLoanPayment();
        Test.stopTest();
    }
    
    @isTest static void test_method_WSLoanPayments_v1_6() {
        // Implement test code
        createData();
        String loanId = loanAccount.Id;
        Map<String,Object> reqBodyMap = new Map<String,Object>();
        reqBodyMap.put('contractId', loanId);
        reqBodyMap.put('cardNumber', '1234');
        reqBodyMap.put('cvv', '1234');
        reqBodyMap.put('month', null);
        RestRequest req  = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/v1/payments';
        req.requestBody = Blob.valueOf(JSON.serialize(reqBodyMap));
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        Response results = WSLoanPayments.createLoanPayment();
        Test.stopTest();
    }

    @isTest static void test_method_WSLoanPayments_v1_7() {
        // Implement test code
        createData();
        String loanId = loanAccount.Id;
        Map<String,Object> reqBodyMap = new Map<String,Object>();
        reqBodyMap.put('contractId', loanId);
        reqBodyMap.put('cardNumber', '1234');
        reqBodyMap.put('cvv', '1234');
        reqBodyMap.put('month', '3');
        RestRequest req  = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/v1/payments';
        req.requestBody = Blob.valueOf(JSON.serialize(reqBodyMap));
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        Response results = WSLoanPayments.createLoanPayment();
        Test.stopTest();
    }

    @isTest static void test_method_WSLoanPayments_v1_8() {
        // Implement test code
        createData();
        String loanId = loanAccount.Id;
        Map<String,Object> reqBodyMap = new Map<String,Object>();
        reqBodyMap.put('contractId', loanId);
        reqBodyMap.put('cardNumber', '1234');
        reqBodyMap.put('cvv', '1234');
        reqBodyMap.put('month', 3);
        reqBodyMap.put('year', null);
        RestRequest req  = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/v1/payments';
        req.requestBody = Blob.valueOf(JSON.serialize(reqBodyMap));
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        Response results = WSLoanPayments.createLoanPayment();
        Test.stopTest();
    }

    @isTest static void test_method_WSLoanPayments_v1_9() {
        // Implement test code
        createData();
        String loanId = loanAccount.Id;
        Map<String,Object> reqBodyMap = new Map<String,Object>();
        reqBodyMap.put('contractId', loanId);
        reqBodyMap.put('cardNumber', '1234');
        reqBodyMap.put('cvv', '1234');
        reqBodyMap.put('month', 3);
        reqBodyMap.put('year', 2016);
        reqBodyMap.put('bankName', null);
        RestRequest req  = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/v1/payments';
        req.requestBody = Blob.valueOf(JSON.serialize(reqBodyMap));
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        Response results = WSLoanPayments.createLoanPayment();
        Test.stopTest();
    }

    @isTest static void test_method_WSLoanPayments_v1_10() {
        // Implement test code
        createData();
        String loanId = loanAccount.Id;
        Map<String,Object> reqBodyMap = new Map<String,Object>();
        reqBodyMap.put('contractId', '123456789123456');
        reqBodyMap.put('cardNumber', '123456');
        reqBodyMap.put('cvv', '123');
        reqBodyMap.put('month', 3);
        reqBodyMap.put('year', 2016);
        reqBodyMap.put('bankName', 'testBANK');
        RestRequest req  = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/v1/payments';
        req.requestBody = Blob.valueOf(JSON.serialize(reqBodyMap));
//        req.(JSON.serializePretty('contractId:'+loanId));
//        req.addParameter('contractId', loanAccount.Id);
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        Response results = WSLoanPayments.createLoanPayment();
        Test.stopTest();
    }
}