src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>loan__Broker__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Tick, if the Account is a Broker.</inlineHelpText>
        <label>Broker</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Broker__c.object
<CustomObject>
    <fields>
        <fullName>loan__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Broker Account for this lending account.</description>
        <inlineHelpText>Broker Account for this lending account.</inlineHelpText>
        <label>Broker Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.loan__Broker__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Brokers</relationshipLabel>
        <relationshipName>Brokers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Commission_Disbursement_Method__c</fullName>
        <description>Method how commission will be disbursed to broker.</description>
        <inlineHelpText>Method how commission will be disbursed to broker.</inlineHelpText>
        <label>Commission Disbursement Method</label>
        <picklist>
            <picklistValues>
                <fullName>Upfront</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Upfront at month end</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pay as received</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>loan__Commission_Till_Date__c</fullName>
        <label>Commission Till Date</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>loan__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Broker Contact for this lending account.</description>
        <inlineHelpText>Broker Contact for this lending account.</inlineHelpText>
        <label>Broker Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.loan__Contact_Type__c</field>
                <operation>equals</operation>
                <value>Broker</value>
            </filterItems>
            <infoMessage>Please select the appropriate broker</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Brokers</relationshipLabel>
        <relationshipName>Brokers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Last_Commission_Date__c</fullName>
        <label>Last Commission Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>loan__Last_Payment_Date__c</fullName>
        <description>Last Payment Date For Commission</description>
        <inlineHelpText>Last Payment Date For Commission.</inlineHelpText>
        <label>Last Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>loan__Last_Principal_Used__c</fullName>
        <label>Last Principal Used For Commission</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>loan__Lending_Account__c</fullName>
        <label>Lending Account</label>
        <referenceTo>loan__Loan_Account__c</referenceTo>
        <relationshipLabel>Brokers</relationshipLabel>
        <relationshipName>Brokers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>loan__Next_Payment_Date__c</fullName>
        <description>Next Payment Date For Commission</description>
        <inlineHelpText>Next Payment Date For Commission.</inlineHelpText>
        <label>Next Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>loan__Total_Commission_Paid_Amount__c</fullName>
        <defaultValue>0.00</defaultValue>
        <description>Commission Paid Amount</description>
        <inlineHelpText>Commission Paid Amount</inlineHelpText>
        <label>Commission Paid Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Broker</label>
    <nameField>
        <displayFormat>LB-{000000000}</displayFormat>
        <label>Broker Record Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brokers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/loan__Broker_Transactions__c.object
<CustomObject>
    <description>Broker Transactions</description>
    <fields>
        <fullName>loan__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Broker Account</description>
        <inlineHelpText>Broker Account</inlineHelpText>
        <label>Broker Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Broker Transactions</relationshipLabel>
        <relationshipName>Broker_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Broker__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup with Broker</description>
        <label>Broker</label>
        <referenceTo>loan__Broker__c</referenceTo>
        <relationshipLabel>Broker Transactions</relationshipLabel>
        <relationshipName>Broker_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Broker Contact</description>
        <inlineHelpText>Broker Contact</inlineHelpText>
        <label>Broker Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Broker Transactions</relationshipLabel>
        <relationshipName>Broker_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Reference__c</fullName>
        <description>Reference</description>
        <inlineHelpText>Reference</inlineHelpText>
        <label>Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>loan__System_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To identify is user posted this transaction manually.</description>
        <inlineHelpText>To identify is user posted this transaction manually.</inlineHelpText>
        <label>System Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>loan__Transaction_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Transaction Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>loan__Transaction_Code__c</fullName>
        <description>Transaction Codes</description>
        <inlineHelpText>Transaction Codes</inlineHelpText>
        <label>Transaction Code</label>
        <picklist>
            <picklistValues>
                <fullName>Commission Disbursement</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Commission Chargeback</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upfront Commission Disbursement</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>loan__Transaction_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>loan__Transaction_Description__c</fullName>
        <defaultValue>&quot;Funds Added&quot;</defaultValue>
        <label>Transaction Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Broker Transaction</label>
    <nameField>
        <displayFormat>BT-{000000000}</displayFormat>
        <label>Broker Transactions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_Account__c.object
<CustomObject>
    <description>Lending Account</description>
    <fields>
        <fullName>loan__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Please choose a account, which will be associated as a customer on this lending account.
You can create a new account, from the lookup window by clicking on new or select the existing account from the lookup.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Loan_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Please choose a contact, which will be associated as a customer on this lending account. 
You can create a new contact, from the lookup window by clicking on new or select the existing contact from the lookup.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Loan_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Last_Payment_Date__c</fullName>
        <description>Date when last payment was received.</description>
        <inlineHelpText>Date when the  last payment was received.</inlineHelpText>
        <label>Last Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>loan__Loan_Status__c</fullName>
        <inlineHelpText>Status of the Account, expected values are :
Pending Approval
Active - Good Standing
Active - Bad Standing
Active - Matured
Approved
Canceled
Closed - Obligations met
Closed- Written Off
Closed - Refinanced
Partial Application</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Partial Application</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active - Good Standing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active - Bad Standing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Obligations met</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed- Written Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Refinanced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active - Matured</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>loan__Principal_Remaining__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Principal/Advance Remaining</description>
        <inlineHelpText>Unpaid Principal/advance balance on the loan account.</inlineHelpText>
        <label>Principal/Advance Remaining</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_Payment_Transaction__c.object
<CustomObject>
    <description>Loan Payment Transaction</description>
    <fields>
        <fullName>loan__Dependent_Payment_Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dependent Payment Transaction</label>
        <referenceTo>loan__Loan_Payment_Transaction__c</referenceTo>
        <relationshipLabel>Loan Payment Transactions</relationshipLabel>
        <relationshipName>Loan_Payment_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Loan_Account__c</fullName>
        <description>Loan Account</description>
        <inlineHelpText>Loan Account</inlineHelpText>
        <label>Loan Account</label>
        <referenceTo>loan__Loan_Account__c</referenceTo>
        <relationshipLabel>Loan Payment Transactions</relationshipLabel>
        <relationshipName>Loan_Payment_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>loan__Paid_to_Broker__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To track whether this payment has been paid to Broker or not.</description>
        <label>Paid to Broker</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>loan__Transaction_Amount__c</fullName>
        <description>Transaction Amount</description>
        <inlineHelpText>This is the sum of Interest, Principal and Fees</inlineHelpText>
        <label>Transaction Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Transaction_Date__c</fullName>
        <defaultValue>$User.loan__Current_Branch_s_System_Date__c</defaultValue>
        <description>Transaction Date</description>
        <inlineHelpText>Transaction Date</inlineHelpText>
        <label>Transaction Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Loan Payment Transaction</label>
    <nameField>
        <displayFormat>LPT-{000000000}</displayFormat>
        <label>Loan Payment Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Payment Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BrokerReverseCommissiondisbJobHandler.cls
public class BrokerReverseCommissiondisbJobHandler {
    private List<loan__Loan_Account__c> loans;
    private List<loan__Loan_Account__c> loanAccToBeUpdatedList;
    private List<loan__Broker__c> brokerlistToBeUpdated;
    private List<loan__Broker_Transactions__c> brokerTransactionsToBeInserted;
    private List<loan__Loan_Payment_Transaction__c> PmtTxnsUpdateList ;
    private Date systemDate;
    
    public BrokerReverseCommissiondisbJobHandler(List<loan__Loan_Account__c> loans,Date systemDate) {
    
        this.loans = loans;
        this.brokerlistToBeUpdated = new List<loan__Broker__c>(); 
        this.PmtTxnsUpdateList = new List<loan__Loan_Payment_Transaction__c>();
        this.loanAccToBeUpdatedList = new List<loan__Loan_Account__c>();
        this.brokerTransactionsToBeInserted = new List<loan__Broker_Transactions__c>();
        this.systemDate = systemDate;
    }
    
    
    public void process() {
        System.debug(logginglevel.error,'Start Processing Broker commission List size'+loans.size());
        
        for(loan__Loan_Account__c loanAccount : loans){
            System.debug(logginglevel.error,'calling postBrokerCommission for:'+loanAccount.name);
            postBrokerCommission(loanAccount);
        }    
        
        System.debug(logginglevel.error,'brokerTransactionsToBeInserted: ' +brokerTransactionsToBeInserted.size());
        System.debug(logginglevel.error,'brokerlistToBeUpdated: ' +brokerlistToBeUpdated.size());
        System.debug('Updating the loan Account');
        
        update loanAccToBeUpdatedList;
        insert brokerTransactionsToBeInserted;
        update brokerlistToBeUpdated;
        update PmtTxnsUpdateList;
        
    }
    
    private void postBrokerCommission(loan__Loan_Account__c loanAccount){
        System.debug(logginglevel.error,'Processing : ' + loanAccount.name);
        
        List<loan__Broker__c> brokerSetupRecs = loanAccount.loan__Brokers__r;
        List<loan__Loan_Payment_Transaction__c> pmtTxnsList = loanAccount.loan__Loan_Payment_Transactions__r;
        Decimal totalCommissionEarned = 0;
        Decimal totalInterestEarned = 0;
        Decimal totalCommissionReversal = 0;
        Date nextCommPaymentDate = loan.LoanConstants.DT_MAX;
        
        System.debug(logginglevel.error,'brokerSetupRecs: ' + brokerSetupRecs);
        
        for(loan__Broker__c brokerSetup : brokerSetupRecs) {
            totalCommissionEarned = 0;
            totalCommissionReversal = 0;
            totalInterestEarned = 0;
            
            System.debug(logginglevel.error,'Commission_Disbursement_Method__c: ' + brokerSetup.loan__Commission_Disbursement_Method__c);
            
            if(brokerSetup.loan__Commission_Disbursement_Method__c.equalsIgnoreCase('Month End') 
                    || brokerSetup.loan__Commission_Disbursement_Method__c.equalsIgnoreCase('Quarterly') ) {
                System.debug('Inside Month End');
                if(loanAccount.loan__Loan_Status__c != loan.LoanConstants.LOAN_STATUSACTIVE_BAD_STANDING) {
                    totalCommissionEarned = brokerSetup.loan__Commission_Till_Date__c;
                    brokerSetup.loan__Commission_Till_Date__c = 0;
                    brokerSetup.loan__Last_Commission_Date__c = systemDate;
                    brokerSetup.loan__Last_Principal_Used__c = loanAccount.loan__Principal_Remaining__c;
                    
                    for(loan__Loan_Payment_Transaction__c pmtTxn : pmtTxnsList){
                        pmtTxn.loan__Paid_to_broker__c = true;
                        PmtTxnsUpdateList.add(pmtTxn);
                    }
                }else{
                    totalCommissionEarned = 0;
                }
            }
            
            totalCommissionEarned = loan.ValueUtil.round(totalCommissionEarned);
            System.debug(logginglevel.error,'totalCommissionEarned: ' + totalCommissionEarned);
            
            //  Total Commission Paid Amount
            if (totalCommissionEarned >0) {
                brokerSetup.loan__Total_Commission_Paid_Amount__c = (brokerSetup.loan__Total_Commission_Paid_Amount__c == null)?0:brokerSetup.loan__Total_Commission_Paid_Amount__c + totalCommissionEarned;
            }
            if (totalCommissionReversal >0){
                brokerSetup.loan__Total_Commission_Paid_Amount__c = (brokerSetup.loan__Total_Commission_Paid_Amount__c == null)?0:brokerSetup.loan__Total_Commission_Paid_Amount__c - totalCommissionReversal;
            }   
            System.debug(logginglevel.error,'brokerSetup.Total_Commission_Paid_Amount__c: ' + brokerSetup.loan__Total_Commission_Paid_Amount__c);
            
            //  Set Next Payment Date
            if (brokerSetup.loan__Commission_Disbursement_Method__c == loan.LoanConstants.PAY_AS_RECEIVED || brokerSetup.loan__Commission_Disbursement_Method__c.equalsIgnoreCase('Month End') ) {
                brokerSetup.loan__Last_Payment_Date__c = brokerSetup.loan__Next_Payment_Date__c;
                brokerSetup.loan__Next_Payment_Date__c = brokerSetup.loan__Next_Payment_Date__c.addMonths(1).toStartOfMonth().addDays(Date.daysInMonth(brokerSetup.loan__Next_Payment_Date__c.addMonths(1).toStartOfMonth().year(), brokerSetup.loan__Next_Payment_Date__c.addMonths(1).toStartOfMonth().month()) - 1);
            }else if(brokerSetup.loan__Commission_Disbursement_Method__c == loan.LoanConstants.UPFRONT_ME){
                brokerSetup.loan__Last_Payment_Date__c = brokerSetup.loan__Next_Payment_Date__c;
                brokerSetup.loan__Next_Payment_Date__c = loan.LoanConstants.DT_MAX;
            }
            //Added by Nachiketh for Quarterly
            else if(brokerSetup.loan__Commission_Disbursement_Method__c.equalsIgnoreCase('Quarterly')){
                brokerSetup.loan__Last_Payment_Date__c = brokerSetup.loan__Next_Payment_Date__c;
                brokerSetup.loan__Next_Payment_Date__c = brokerSetup.loan__Next_Payment_Date__c.addMonths(4).toStartofMonth().addDays(-1); 
            }
            System.debug(logginglevel.error,'brokerSetup.Next_Payment_Date__c: ' + brokerSetup.loan__Next_Payment_Date__c);
            // Commented by Simran - Next Commission Date on Loan Account will be set outside the for loop
            // loanAccount.Next_Commission_Payment_Date__c = (brokerSetup.Next_Payment_Date__c <loanAccount.Next_Commission_Payment_Date__c)?loanAccount.Next_Commission_Payment_Date__c:brokerSetup.Next_Payment_Date__c;
            
            // Added by Simran to get the minimum next payment date
            if (brokerSetup.loan__Next_Payment_Date__c < nextCommPaymentDate)
                nextCommPaymentDate = brokerSetup.loan__Next_Payment_Date__c;
            
            brokerlistToBeUpdated.add(brokerSetup);
            
            if (totalCommissionEarned > 0){
                loan__Broker_Transactions__c brokerTxn = new loan__Broker_Transactions__c(); 
                brokerTxn.loan__Transaction_Amount__c = totalCommissionEarned;
                brokerTxn.loan__Transaction_Date__c = systemDate;
                brokerTxn.loan__Reference__c = 'Commission disbursement for '+loanAccount.name;
                brokerTxn.loan__Transaction_Description__c = loan.loanConstants.TXN_COMMISSION_DISB;
                brokerTxn.loan__Transaction_Code__c = loan.loanConstants.TXN_COMMISSION_DISB;
                brokerTxn.loan__System_Created__c = true;
                brokerTxn.loan__Account__c = brokerSetup.loan__Account__c;
                brokerTxn.loan__Contact__c = brokerSetup.loan__Contact__c;
                brokerTxn.loan__Broker__c = brokerSetup.id;
                brokerTransactionsToBeInserted.add(brokerTxn);
            }else if (totalCommissionReversal !=0 ){
                loan__Broker_Transactions__c brokerTxn = new loan__Broker_Transactions__c(); 
                brokerTxn.loan__Transaction_Amount__c = totalCommissionReversal.abs();
                brokerTxn.loan__Transaction_Date__c = systemDate;
                brokerTxn.loan__Reference__c = 'Commission Chargeback for '+loanAccount.name;
                brokerTxn.loan__Transaction_Description__c = loan.loanConstants.TXN_COMMISSION_CGBK;
                brokerTxn.loan__Transaction_Code__c = loan.loanConstants.TXN_COMMISSION_CGBK;
                brokerTxn.loan__System_Created__c = true;
                brokerTxn.loan__Account__c = brokerSetup.loan__Account__c;
                brokerTxn.loan__contact__c = brokerSetup.loan__Contact__c;
                brokerTxn.loan__Broker__c = brokerSetup.id;
                brokerTransactionsToBeInserted.add(brokerTxn);
            }
            
        }
        // Added by Simran - set Next Commission Payment date on Loan Account
        System.debug(logginglevel.error,'nextCommPaymentDate: ' + nextCommPaymentDate );
        loanAccount.loan__Next_Commission_Payment_Date__c = nextCommPaymentDate ;
        loanAccToBeUpdatedList.add(loanAccount);
            
    }
    
}