src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>loan__Active__c</fullName>
        <label>Active</label>
        <picklist>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Bank_Account__c.object
<CustomObject>
    <fields>
        <fullName>Bank_Card_Details__c</fullName>
        <label>Card Number</label>
        <length>20</length>
        <maskChar>X</maskChar>
        <maskType>creditCard</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>CVV__c</fullName>
        <label>Security Code</label>
        <length>3</length>
        <maskChar>X</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Expiry_Month__c</fullName>
        <label>Expiry Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expiry_Year__c</fullName>
        <label>Expiry Year</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Account_Type__c</fullName>
        <label>Account Type</label>
        <picklist>
            <picklistValues>
                <fullName>Saving</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checking</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>loan__Account_Usage__c</fullName>
        <label>Account Usage</label>
        <picklist>
            <picklistValues>
                <fullName>Investor Trust Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collections Trust Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advance Trust Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tax Withholding Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Borrower/Investor Account</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>loan__Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>loan__Bank_Account_Number__c</fullName>
        <label>Bank Account Number</label>
        <length>50</length>
        <maskChar>X</maskChar>
        <maskType>lastFour</maskType>
        <required>true</required>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>loan__Bank_Name__c</fullName>
        <label>Bank Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>loan__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bank Accounts</relationshipLabel>
        <relationshipName>Bank_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Bank Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_Account__c.object
<CustomObject>
    <description>Lending Account</description>
    <fields>
        <fullName>loan__Account_Type__c</fullName>
        <label>Account Type</label>
        <picklist>
            <picklistValues>
                <fullName>Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Type2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>loan__Borrower_ACH__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Borrower ACH</description>
        <inlineHelpText>Borrower ACH</inlineHelpText>
        <label>Borrower ACH</label>
        <referenceTo>loan__Bank_Account__c</referenceTo>
        <relationshipName>Lending</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Please choose a contact, which will be associated as a customer on this lending account. 
You can create a new contact, from the lookup window by clicking on new or select the existing contact from the lookup.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Loan_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Credit_Limit__c</fullName>
        <description>Credit Limit for Line of Credit</description>
        <inlineHelpText>This is the contractual maximum advance limit, total advance withdrawn must not exceed this limit.</inlineHelpText>
        <label>Credit Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Loan_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Loan Amount</description>
        <inlineHelpText>This is the financed amount on the contract which will be disbursed to the customer.</inlineHelpText>
        <label>Loan Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WSBankDetails_v1.cls
@RestResource(urlMapping='/v1/bankDetails')
global class WSBankDetails_v1 {

    @HttpPost
    global static Response createBankAccount() {
        RestRequest req = RestContext.request;
        RestResponse restRes = RestContext.response;
        Response res = new Response();
        
        System.debug(LoggingLEvel.ERROR,' Request Received '+req);
        
        RequestBodyParser.RequestBodyParams reqParams = RequestBodyParser.getJsonParamsFromRequest(req);
        if(reqParams == null) {
            
            res.errorCode = peer.Constants.INVALID_INPUT;
            res.status = peer.Constants.ERROR;
            res.errorMessage = 'Unable to parse request';
            restRes.statuscode = peer.Constants.HTTP_BAD_REQUEST;
            return res;
        }
        
        Map<String, Object> params = reqParams.getParams();
        String contractId = null;
        String cardNumber = null;
        String cvv = null;
        Integer month = null;
        Integer year = null;
        String bankName = null;
        Date systemDate;
        
        loan.GlobalLoanUtilFacade f = new loan.GlobalLoanUtilFacade();
        systemDate = f.getCurrentSystemDate();
        
        try {
            if (params.get('contractId') != null) {
                contractId = (String)params.get('contractId');
            }
            if(params.get('cardNumber') != null) {
                cardNumber = (String)params.get('cardNumber');
            }
            if(params.get('cvv') != null) {
                cvv = (String)params.get('cvv');
            }
            if(params.get('month') != null) {
                month = (Integer)params.get('month');
            }
            if(params.get('year') != null) {
                year = (Integer)params.get('year');
            }
            if(params.get('bankName') != null){
                bankName = (String)params.get('bankName');
            }
        }catch(Exception e) {
            res.errorCode = peer.Constants.INVALID_INPUT;
            res.status = peer.Constants.ERROR;
            res.errorMessage = 'Error while parsing request parameters.';
            restRes.statuscode = peer.Constants.HTTP_BAD_REQUEST;
            return res;
        }

        if(contractId == null){
            res.errorCode = peer.Constants.INVALID_INPUT;
            res.status = peer.Constants.ERROR;
            res.errorMessage = 'ContractId can not be null';
            restRes.statuscode = peer.Constants.HTTP_BAD_REQUEST;
            return res;
        } 
        
        if(cardNumber == null) {
            res.errorCode = peer.Constants.INVALID_INPUT;
            res.status = peer.Constants.ERROR;
            res.errorMessage = 'Card Number can not be null';
            restRes.statuscode = peer.Constants.HTTP_BAD_REQUEST;
            return res;
        }
        
        if(cvv == null) {
            res.errorCode = peer.Constants.INVALID_INPUT;
            res.status = peer.Constants.ERROR;
            res.errorMessage = 'Cvv can not be null';
            restRes.statuscode = peer.Constants.HTTP_BAD_REQUEST;
            return res;
        }
        
        if(month == null) {
            res.errorCode = peer.Constants.INVALID_INPUT;
            res.status = peer.Constants.ERROR;
            res.errorMessage = 'Month can not be null';
            restRes.statuscode = peer.Constants.HTTP_BAD_REQUEST;
            return res;
        }
        
        if(year == null) {
            res.errorCode = peer.Constants.INVALID_INPUT;
            res.status = peer.Constants.ERROR;
            res.errorMessage = 'Year can not be null';
            restRes.statuscode = peer.Constants.HTTP_BAD_REQUEST;
            return res;
        }
        
        //Fetch LOC
        List<loan__Loan_Account__c> locContracts = [Select Id,Name,
                                                           loan__Contact__c,
                                                           loan__Contact__r.Name,
                                                           loan__Contact__r.FirstName,
                                                           loan__Contact__r.LastName,
                                                           loan__Loan_Amount__c,
                                                           loan__Credit_Limit__c,
                                                           loan__Borrower_ACH__c
                                                    From loan__Loan_Account__c
                                                    Where Id =: contractId];
        
        if (locContracts.isEmpty()) {
            res.errorCode = 'CONTRACT_NOT_FOUND';
            res.status = peer.Constants.ERROR;
            res.errorMessage = 'LOC Contract not found for given ID';
            restRes.statuscode = peer.Constants.HTTP_BAD_REQUEST;
            return res;

        } 
                                                    
        loan__Loan_Account__c locRec = locContracts[0];  
        loan__Bank_Account__c bankAcc;
        loan__bank_Account__c oldBank;
        
        try{
            //If bank Account already exists, Disable old one & create new rec.
            if(locRec.loan__Borrower_ACH__c != null){
                oldBank = [Select Id,Name,
                                  loan__Active__c,
                                  Bank_Card_Details__c,
                                  Expiry_Month__c,
                                  Expiry_year__c
                           From loan__Bank_Account__c Where Id =: locRec.loan__Borrower_ACH__c];
                oldBank.loan__Active__c = false;
                update oldBank;
            }
            
            //Create New
            bankAcc = new loan__Bank_Account__c();
            bankAcc.loan__Contact__c = locRec.loan__Contact__c;
            bankAcc.Bank_Card_Details__c = cardNumber;
            bankAcc.Cvv__c = cvv;
            bankAcc.expiry_Month__c = month;
            bankAcc.Expiry_year__c = year;
            bankAcc.loan__Account_Usage__c = 'Borrower/Investor Account';
            bankAcc.loan__Active__c = true;
            bankAcc.loan__Account_Type__c = 'Savings';
            bankAcc.loan__Bank_Account_Number__c = cardNumber;
            bankAcc.loan__Bank_Name__c = (bankName != null) ? bankName :'Visa';
            
            insert bankAcc;
            
            locRec.loan__Borrower_ACH__c = bankAcc.Id;
            update locRec;
                                                              
        }Catch(Exception e){
            System.debug(LoggingLevel.ERROR,' Error : Bank Details '+e.getMessage()+' from line '+e.getLineNumber());
            res.errorCode = peer.Constants.API_EXCEPTION;
            res.errorMessage = e.getMessage()+' From line '+e.getLineNumber();
            res.status = peer.Constants.ERROR;
            restRes.statuscode = peer.Constants.HTTP_INTERNAL_ERROR;
            return res;  
        }
        
        res.content.add(bankAcc);
        if(oldBank != null) {
            res.content.add(oldBank);
        }
        res.status = peer.Constants.SUCCESS;
        restRes.statuscode = peer.Constants.HTTP_OK;
        return res;
    }
}