src/objects/cnotify__Notification__c.object
<CustomObject>
    <fields>
        <fullName>CL_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CL Contract</label>
        <referenceTo>loan__Loan_Account__c</referenceTo>
        <relationshipLabel>Notifications</relationshipLabel>
        <relationshipName>Notifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>cnotify__Target_Object_Id__c</fullName>
        <label>Target Object Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Notification</label>
    <nameField>
        <displayFormat>N-{00000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NotificationTriggerHandler.cls
/* 
* Handler class for NotificationTrigger.
* 
* Functions:
* Before Insert : 1. Assigns Target Object Record to Lookup.
*                 
*/
public with sharing class NotificationTriggerHandler {
    private List<cnotify__Notification__c> newList;
    private Map<Id,cnotify__Notification__c> oldMap;
    
    public NotificationTriggerHandler(List<cnotify__Notification__c> newList, Map<Id,cnotify__Notification__c> oldMap){
        this.newList = newList;
        this.oldMap = oldMap;
    }
    
    public void beforeInsertHandler(){
        
        /*
        * assignes Loan Account record to notification.
        */
        for(cnotify__Notification__c notification : newList){
            notification.CL_Contract__c = notification.cnotify__Target_Object_Id__c;
        }
    }
}