src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>loan__Payment_Mode__c</fullName>
        <description>Payment mode, used to disburse payments back to broker.</description>
        <inlineHelpText>Payment mode, used to disburse payments back to broker.</inlineHelpText>
        <label>Payment Mode</label>
        <picklist>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Datacash_Config__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Server_Url__c</fullName>
        <label>Server Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Datacash Configuration</label>
</CustomObject>

src/objects/loan__Bank_Account__c.object
<CustomObject>
    <fields>
        <fullName>Bank_Card_Details__c</fullName>
        <label>Card Number</label>
        <length>20</length>
        <maskChar>X</maskChar>
        <maskType>creditCard</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>CVV__c</fullName>
        <label>Security Code</label>
        <length>3</length>
        <maskChar>X</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Expiry_Month__c</fullName>
        <label>Expiry Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expiry_Year__c</fullName>
        <label>Expiry Year</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>loan__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bank Accounts</relationshipLabel>
        <relationshipName>Bank_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Bank Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Batch_Process_Log__c.object
<CustomObject>
    <fields>
        <fullName>loan__Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>loan__Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Batch Process Log</label>
    <nameField>
        <label>Apex Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Process Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_Account__c.object
<CustomObject>
    <description>Lending Account</description>
    <fields>
        <fullName>loan__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Please choose a contact, which will be associated as a customer on this lending account. 
You can create a new contact, from the lookup window by clicking on new or select the existing contact from the lookup.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Loan_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_Payment_Transaction__c.object
<CustomObject>
    <description>Loan Payment Transaction</description>
    <fields>
        <fullName>loan__Loan_Account__c</fullName>
        <description>Loan Account</description>
        <inlineHelpText>Loan Account</inlineHelpText>
        <label>Loan Account</label>
        <referenceTo>loan__Loan_Account__c</referenceTo>
        <relationshipLabel>Loan Payment Transactions</relationshipLabel>
        <relationshipName>Loan_Payment_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>loan__Payment_Mode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Mode</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>loan__Payment_Mode__c.Name</field>
                <operation>notEqual</operation>
                <value>Internal Transfer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>loan__Payment_Mode__c</referenceTo>
        <relationshipLabel>Loan Payment Transactions</relationshipLabel>
        <relationshipName>Loan_Payment_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Loan Payment Transaction</label>
    <nameField>
        <displayFormat>LPT-{000000000}</displayFormat>
        <label>Loan Payment Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Payment Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/loan__Payment_Mode__c.object
<CustomObject>
    <label>Payment Mode</label>
    <nameField>
        <label>Payment Mode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Mode</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LoanPaymentReversalSweepToDatacash.cls
public class LoanPaymentReversalSweepToDatacash implements Database.Batchable<sObject>, Schedulable,  Database.AllowsCallouts {
    private String query;
    private List<loan__Loan_Payment_Transaction__c> loanPayments;
    private Map<Id,String> invalidPaymentsErrors;
    private List<loan__Loan_Payment_Transaction__c> validPayments;
    private loan__Payment_Mode__c pMode;
    private List<loan__Batch_Process_Log__c> blogs;
    private loan.GlobalLoanUtilFacade facade;
    private Date sysDate;
    private Map<Id,loan__Bank_Account__c> borrowerCardDetailsMap;
    private Datacash_Config__c config;
    
    /* Constructor */
    public LoanPaymentReversalSweepToDatacash() {
        
        facade = new loan.GlobalLoanUtilFacade();
        sysDate = facade.getCurrentSystemDate();
        
        this.query = ProcessJobQueryUtil.getRefundJobQuery(sysDate);
        SYSTEM.DEBUG('###########################'+query);
        
        invalidPaymentsErrors = new Map<Id,String>();
        validPayments = new List<loan__Loan_Payment_Transaction__c>();
        borrowerCardDetailsMap = new Map<Id,loan__Bank_Account__c>();
        bLogs = new List<loan__Batch_Process_Log__c>();
        
        //get custom setting details to Send payment to Datacash
        config = Datacash_Config__c.getOrgDefaults();   
    
    }
    
    public void execute(SchedulableContext sc) {
        
    }
        
    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bc, List<sObject> scope) {
       
        loanPayments = (List<loan__Loan_Payment_Transaction__c>) scope;
        loan__Batch_Process_Log__c errorLog;
        
        Set<ID> contactIds = new Set<ID>();
        
        //Prepare list of Borrowers & its Card Details.
        for(loan__Loan_Payment_Transaction__c lpt : loanPayments) {
            contactIds.add(lpt.loan__Loan_Account__r.loan__Contact__c);
        }
        
        List<Contact> borrowers = [Select Id,Name,
                                          (Select Id,Name,
                                                  Bank_Card_Details__c,
                                                  Expiry_Month__c,
                                                  Expiry_Year__c,
                                                  CVV__c,
                                                  loan__Active__c
                                           from loan__Bank_Accounts__r
                                           Where loan__Active__c = true)
                                   From Contact
                                   Where Id in :contactIds];
        
        for(Contact c : borrowers) {
            if(c.loan__Bank_Accounts__r != null && !c.loan__Bank_Accounts__r.isEmpty()) {
                borrowerCardDetailsMap.put(c.Id,c.loan__Bank_Accounts__r[0]);
            }
        }
        
        //Send Payments To Datacash
        try{
            loan__Bank_Account__c activeCard;
            String endPoint = config.Server_Url__c;
            String username = config.Username__c;
            String password = config.password__c;
            
            BorrowerImpl impl = new BorrowerImpl();
            
            for(loan__Loan_Payment_Transaction__c lpt : loanPayments) {
                activeCard = borrowerCardDetailsMap.get(lpt.loan__Loan_Account__r.loan__Contact__c);
                
                if(activeCard == null) {
                    //Card details not found. Add to invalid transaction.
                    invalidPaymentsErrors.put(lpt.Id,' Active Card is not available for payments. Please contact borrower.');
                }else {
                    //Send to Datacash.
                    PaymentTransactionResponse payResponse = impl.sendPaymentToDataCashRefund(endpoint,
                                                                                              username,
                                                                                              password,
                                                                                              activeCard,lpt);
                    
                    System.debug(LoggingLevel.ERROR,' Res '+payResponse);
                    
                    //If Response is success, 
                    if(payResponse.successMessage.equals('SUCCESS')) {
                        validPayments.add(payResponse.lpt);
                    }else {
                        System.debug(LoggingLevel.ERROR,'Invalid Response ');
                        invalidPaymentsErrors.put(lpt.Name,payResponse.responseBody);
                    }                                                                        
                }
            }
            
            //Create Batch Process logs for failed payments for any reason & update valid loanpayments
            update validPayments;
            
            for(String lptName : invalidPaymentsErrors.keyset()) {
                
                errorLog = new loan__Batch_Process_Log__c();
                errorLog.loan__Message__c = 'Datacash Refund processing failed for '+lptName+'. Error: '+invalidPaymentsErrors.get(lptName);
                errorLog.loan__Date__c = Date.newInstance(System.now().year(),System.now().month(),System.now().day());
                bLogs.add(errorLog);
                
            }
            
            insert bLogs;
            
        }catch(Exception e) {
            errorLog = new loan__Batch_Process_Log__c();
            errorLog.loan__Message__c = 'Error : LoanPaymentTransactionAchJob: '+e.getMessage()+' from line '+e.getLineNumber();
            errorLog.loan__Date__c = Date.newInstance(System.now().year(),System.now().month(),System.now().day());
            
            bLogs.add(errorLog);
            insert bLogs;
        }
    }
    
    public void finish(Database.BatchableContext bc){
    
    }
}