src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>loan__Payment_Mode__c</fullName>
        <description>Payment mode, used to disburse payments back to broker.</description>
        <inlineHelpText>Payment mode, used to disburse payments back to broker.</inlineHelpText>
        <label>Payment Mode</label>
        <picklist>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/loan__Currency__c.object
<CustomObject>
    <description>Currency</description>
    <label>Currency</label>
    <nameField>
        <label>Currency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Fee__c.object
<CustomObject>
    <description>Fee</description>
    <fields>
        <fullName>loan__Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Currency</description>
        <inlineHelpText>Currency</inlineHelpText>
        <label>Currency</label>
        <referenceTo>loan__Currency__c</referenceTo>
        <relationshipLabel>Fees</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fee</label>
    <nameField>
        <label>Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Fee_Junction__c.object
<CustomObject>
    <fields>
        <fullName>loan__Fee_Set__c</fullName>
        <label>Fee Set</label>
        <referenceTo>loan__Fee_Set__c</referenceTo>
        <relationshipName>Fee_Junction</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>loan__Fee__c</fullName>
        <label>Fee</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>loan__Fee__c.loan__Time_of_charge__c</field>
                <operation>notEqual</operation>
                <value>Pre-Paid Fees</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>loan__Fee__c</referenceTo>
        <relationshipLabel>Fee Set/Fee</relationshipLabel>
        <relationshipName>Fee_Junction</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Fee Set/Fee</label>
    <nameField>
        <displayFormat>FJIP-{0000000000}</displayFormat>
        <label>Fee Junction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fee Set/Fee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/loan__Fee_Set__c.object
<CustomObject>
    <description>A set of fee</description>
    <label>Fee Set</label>
    <nameField>
        <label>Fee Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fee Set</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_Account__c.object
<CustomObject>
    <description>Lending Account</description>
    <fields>
        <fullName>loan__Fee_Set__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Fee Set</description>
        <inlineHelpText>Lookup to associate the fee set on this lending account. Only the fees defined within the fee set can be assessed on this contract.
To create a fee set, Servicing configuration-&gt;Product-&gt;Manage fee set</inlineHelpText>
        <label>Fee Set</label>
        <referenceTo>loan__Fee_Set__c</referenceTo>
        <relationshipName>Loan_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Loan_Purpose__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Loan Purpose</description>
        <inlineHelpText>Loan purpose</inlineHelpText>
        <label>Purpose</label>
        <referenceTo>loan__Loan_Purpose__c</referenceTo>
        <relationshipName>Loan_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Payment_Application_Mode__c</fullName>
        <description>If the value is Future Dues, Reserve Amount For Next Due will be used for satisfying Bills. Otherwise, Reserve Amount For Next Due will not be used for satisfying Bills.</description>
        <inlineHelpText>Possible values are 
1) Future Dues
2) Current Dues
Future Dues is used when Loan Payments should be used to satisfy future dues.
Current Dues is used when Loan Payments should only be used to satisfy present dues.</inlineHelpText>
        <label>Payment Application Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Future Dues</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Current Dues</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_Product__c.object
<CustomObject>
    <description>Lending Product Definition1</description>
    <fields>
        <fullName>loan__Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Currency</description>
        <inlineHelpText>Currency</inlineHelpText>
        <label>Currency</label>
        <referenceTo>loan__Currency__c</referenceTo>
        <relationshipName>Loan_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Fee_Set__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fee Set</description>
        <inlineHelpText>Fee set contains the details of all the fees associated with the loan.</inlineHelpText>
        <label>Fee Set</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected Fee Set&apos;s category must be of type &apos;Loan&apos; and it should include at least one fee.</errorMessage>
            <filterItems>
                <field>loan__Fee_Set__c.loan__Fee_Set_Category__c</field>
                <operation>equals</operation>
                <value>Loan</value>
            </filterItems>
            <filterItems>
                <field>loan__Fee_Set__c.loan__Number_of_Fees__c</field>
                <operation>notEqual</operation>
                <value>0</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>loan__Fee_Set__c</referenceTo>
        <relationshipName>Loan_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Payment_Application_Mode__c</fullName>
        <description>If the value is Future Dues, Reserve Amount For Next Due will be used for satisfying Bills. Otherwise, Reserve Amount For Next Due will not be used for satisfying Bills.</description>
        <inlineHelpText>Select Future Dues if the loan payments must be used to satisfy future dues. 
 Select Current Dues if the loan payments must be used to to satisfy present dues.</inlineHelpText>
        <label>Payment Application Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Future Dues</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Current Dues</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Lending Product</label>
    <nameField>
        <label>Loan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lending Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_Purpose__c.object
<CustomObject>
    <description>Loan Purpose</description>
    <label>Loan Purpose</label>
    <nameField>
        <label>Loan Purpose Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Purpose</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__MF_Account__c.object
<CustomObject>
    <label>GL Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Office_Name__c.object
<CustomObject>
    <description>Name of the office</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Payment_Mode__c.object
<CustomObject>
    <label>Payment Mode</label>
    <nameField>
        <label>Payment Mode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Mode</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Virtual_Card__c.object
<CustomObject>
    <fields>
        <fullName>Card_Reference__c</fullName>
        <label>Card Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_Account__c</fullName>
        <label>CL Contract</label>
        <referenceTo>loan__Loan_Account__c</referenceTo>
        <relationshipLabel>Virtual Cards</relationshipLabel>
        <relationshipName>Virtual_Cards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Virtual Card</label>
    <nameField>
        <label>Virtual Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Virtual Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestFundingAccountActivityParser.cls
@istest
public class TestFundingAccountActivityParser {

    public static String testString = 'startDate,transactionDate,community,client,transactionID,adjustmentID,transactionType,transactionCurrency,transactionAmount,sourceType,sourceDetails,destinationType,destinationDetails,participantType,participantDetails,participantSink,originalCurrency,originalAmount,participantCurrency,participantAmount,exchangeRate,nonForexFee,forexFee,balanceBefore,balanceAdjustment,balanceAfter,status,forexFlag,direction,merchantName,merchantCountry,merchantCategoryCode,acquirerReferenceNumber,authCode,providerDate,externalRef,externalID,cardNum,cardScheme,cardFactoryName,customField1,customField2,customField3,customField4,customField5,transactionInfo,scenarioCases,singleCases'+ '\n' +
                    '07/07/14 19:02,07/07/14 19:02,ClientA,ClientA#ClientA,9.21E+16,9.21E+16,CARD CREATED,EUR,636.84,Funding Account,faClientAEUR,Virtual Card,ClientAvisa.P6HDHM3RR40,Virtual Card,ClientAvisa.P6HDHM3RR40,DESTINATION,EUR,636.84,EUR,636.84,1,0,0,0,636.84,636.84,COMPLETED,N,A,,,,,,,0UwEa4KEnDGEemjzji0aoq_Kv,,446221******2485,VISA,ClientAvisa,,,,,,,5100,1200'+'\n' +
                    '08/07/14 16:09,08/07/14 16:09,ClientA,ClientA#ClientA,9.21E+16,,AUTHORISATION,EUR,-606.51,Virtual Card,ClientAvisa.P6HDHM3RR40,,,Virtual Card,ClientAvisa.P6HDHM3RR40,SOURCE,EUR,-606.51,EUR,0,1,0,0,0,0,0,COMPLETED,N,A,AIR ONE CALL CENTER      ROMA       RMIT,IT,3013,,929566,07/07/14 0:00,0UwEa4KEnDGEemjzji0aoq_Kv,,446221******2485,VISA,ClientAvisa,,,,,,NORMAL_TAKE,5100,1400'+'\n' +
                    '11/07/14 16:11,11/07/14 16:11,ClientA,ClientA#ClientA,9.21E+16,9.21E+16,PURCHASE,EUR,-25,Virtual Card,ClientAvisa.P6HDHM3RR40,,,Virtual Card,ClientAvisa.P6HDHM3RR40,SOURCE,EUR,-25,EUR,-25,1,0,0,636.84,-25,611.84,COMPLETED,N,A,AIR ONE CAL 0554707171442/AIR ONE CALL/,IT,3013,7.49E+22,929566,11/07/14 0:00,0UwEa4KEnDGEemjzji0aoq_Kv,,446221******2485,VISA,ClientAvisa,,,,,,,5100,1600'+'\n' +
                    '11/07/14 16:11,11/07/14 16:11,ClientA,ClientA#ClientA,9.21E+16,9.21E+16,PURCHASE,EUR,-187.04,Virtual Card,ClientAvisa.P6HDHM3RR40,,,Virtual Card,ClientAvisa.P6HDHM3RR40,SOURCE,EUR,-187.04,EUR,-187.04,1,0,0,611.84,-187.04,424.8,COMPLETED,N,A,AIR ONE CAL 0558502885871/AIR ONE CALL/,IT,3013,7.49E+22,929566,11/07/14 0:00,0UwEa4KEnDGEemjzji0aoq_Kv,,446221******2485,VISA,ClientAvisa,,,,,,,5100,1600'+'\n' +
                    '11/07/14 16:11,11/07/14 16:11,ClientA,ClientA#ClientA,9.21E+16,9.21E+16,PURCHASE,EUR,-187.04,Virtual Card,ClientAvisa.P6HDHM3RR40,,,Virtual Card,ClientAvisa.P6HDHM3RR40,SOURCE,EUR,-187.04,EUR,-187.04,1,0,0,424.8,-187.04,237.76,COMPLETED,N,A,AIR ONE CAL 0558502885872/AIR ONE CALL/,IT,3013,7.49E+22,929566,11/07/14 0:00,0UwEa4KEnDGEemjzji0aoq_Kv,,446221******2485,VISA,ClientAvisa,,,,,,,5100,1600'+'\n' +
                    '11/07/14 16:11,11/07/14 16:11,ClientA,ClientA#ClientA,9.21E+16,9.21E+16,PURCHASE,EUR,-25,Virtual Card,ClientAvisa.P6HDHM3RR40,,,Virtual Card,ClientAvisa.P6HDHM3RR40,SOURCE,EUR,-25,EUR,-25,1,0,0,237.76,-25,212.76,COMPLETED,N,A,AIR ONE CAL 0554707171441/AIR ONE CALL/,IT,3013,7.49E+22,929566,11/07/14 0:00,0UwEa4KEnDGEemjzji0aoq_Kv,,446221******2485,VISA,ClientAvisa,,,,,,,5100,1600'+'\n' +
                    '11/07/14 16:11,11/07/14 16:11,ClientA,ClientA#ClientA,9.21E+16,9.21E+16,PURCHASE,EUR,-182.43,Virtual Card,ClientAvisa.P6HDHM3RR40,,,Virtual Card,ClientAvisa.P6HDHM3RR40,SOURCE,EUR,-182.43,EUR,-182.43,1,0,0,212.76,-182.43,30.33,COMPLETED,N,A,AIR ONE CAL 0558502885873/AIR ONE CALL/,IT,3013,7.49E+22,929566,11/07/14 0:00,0UwEa4KEnDGEemjzji0aoq_Kv,,446221******2485,VISA,ClientAvisa,,,,,,,5100,1600'+'\n' +
                    '11/07/14 16:16,11/07/14 16:16,ClientA,ClientA#ClientA,9.21E+16,9.21E+16,CARD DELETED,EUR,30.33,Virtual Card,ClientAvisa.P6HDHM3RR40,Funding Account,faClientAEUR,Virtual Card,ClientAvisa.P6HDHM3RR40,SOURCE,EUR,-30.33,EUR,-30.33,1,0,0,30.33,-30.33,0,COMPLETED,N,A,,,,,,,0UwEa4KEnDGEemjzji0aoq_Kv,,446221******2485,VISA,ClientAvisa,,,,,,,5100,1300'+'\n' +
                    '22/07/14 10:38,22/07/14 10:38,ClientG,ClientD#ClientD,9.21E+16,,CARD CREATED,GBP,0,Funding Account,faClientDGBP,Virtual Card,30e680b7-77ab-4802-aa9b-93c20668df66,Virtual Card,30e680b7-77ab-4802-aa9b-93c20668df66,DESTINATION,GBP,0,GBP,0,1,0,0,0,0,0,COMPLETED,N,A,,,,,,,0UwGIveFM8bGAFst_X5yyfNpQ,,446221******1996,VISA,vsdeb18mss,,,,,,,5200,1205'+'\n' +
                    '22/07/14 10:38,22/07/14 10:38,ClientG,ClientD#ClientD,9.21E+16,9.21E+16,TRANSFER,GBP,275.96,Funding Account,faClientDGBP,Virtual Card,30e680b7-77ab-4802-aa9b-93c20668df66,Virtual Card,30e680b7-77ab-4802-aa9b-93c20668df66,DESTINATION,GBP,275.96,GBP,275.96,1,0,0,0,275.96,275.96,COMPLETED,N,A,,,,,,,0UwGIveFM8bGAFst_X5yyfNpQ,,446221******1996,VISA,vsdeb18mss,,,,,,,5200,100'+'\n' +
                    '23/07/14 16:06,23/07/14 16:06,ClientG,ClientD#ClientD,9.22E+16,,AUTHORISATION,GBP,-275.96,Virtual Card,30e680b7-77ab-4802-aa9b-93c20668df66,,,Virtual Card,30e680b7-77ab-4802-aa9b-93c20668df66,SOURCE,GBP,-275.96,GBP,0,1,0,0,0,0,0,COMPLETED,N,A,AER LINGUS               DUBLIN       IE,IE,3043,,153173,22/07/14 0:00,0UwGIveFM8bGAFst_X5yyfNpQ,,446221******1996,VISA,vsdeb18mss,,,,,,NORMAL_TAKE,5200,1400'+'\n' +
                    '25/07/14 16:12,25/07/14 16:12,ClientG,ClientD#ClientD,9.22E+16,9.22E+16,PURCHASE,GBP,-275.96,Virtual Card,30e680b7-77ab-4802-aa9b-93c20668df66,,,Virtual Card,30e680b7-77ab-4802-aa9b-93c20668df66,SOURCE,GBP,-275.96,GBP,-275.96,1,0,0,275.96,-275.96,0,COMPLETED,N,A,AERLING     23RS2F TESTER/DUBLIN/,GB,3043,7.41E+22,153173,25/07/14 0:00,0UwGIveFM8bGAFst_X5yyfNpQ,,446221******1996,VISA,vsdeb18mss,,,,,,,5200,1600'+'\n' +
                    '25/07/14 16:12,25/07/14 16:12,ClientG,ClientD#ClientD,9.22E+16,,CARD DELETED,GBP,0,Virtual Card,30e680b7-77ab-4802-aa9b-93c20668df66,Funding Account,faClientDGBP,Virtual Card,30e680b7-77ab-4802-aa9b-93c20668df66,SOURCE,GBP,0,GBP,0,1,0,0,0,0,0,COMPLETED,N,A,,,,,,,0UwGIveFM8bGAFst_X5yyfNpQ,,446221******1996,VISA,vsdeb18mss,,,,,,,5200,1302'+ '\n' +
                    '30/07/14 16:10,30/07/14 16:10,ClientG,ClientD#ClientD,9.22E+16,9.22E+16,MERCHANT REFUND,GBP,100,,,Virtual Card,0RACI_D8GBZeiKne-aQDNwV52,Virtual Card,30e680b7-77ab-4802-aa9b-93c20668df66,DESTINATION,GBP,72,GBP,72,1,0,0,0,72,72,COMPLETED,N,A,AER LINGUCB/DUBLIN/,GB,3043,7.41E+22,1100,30/07/14 0:00,0UwGIveFM8bGAFst_X5yyfNpQ,,446221******1996,VISA,vsdeb18mss,,,,,,,5200,1700';
    public static loan__Loan_Account__c loanAccount;
    
    @testSetup static void createSeedData() {
        System.debug(LoggingLevel.eRROR,' running test data ');
        loan.TestHelper.createSeedDataForTesting();
        
        loan__Currency__c curr = loan.TestHelper.createCurrency();
        //Create a dummy MF_Account
        loan__MF_Account__c dummyAccount = loan.TestHelper.createMFAccount('XXXAccountForTest','10000 - ASSETS');
        loan__MF_Account__c dummyIncAccount = loan.TestHelper.createMFAccount('XXXIncAccountForTest','30000 - INCOME');
        
        //Create a Fee Set
        loan__Fee__c dummyFee = loan.TestHelper.createFee(curr,dummyIncAccount ,dummyAccount);                                    
        loan__Fee_Set__c dummyFeeSet = loan.TestHelper.createFeeSet();
        loan__Fee_Junction__c dummyFeeJunction = loan.TestHelper.createFeeJunction(dummyFee,dummyFeeSet);
        
        loan__Office_Name__c dummyOffice = loan.TestHelper.createOffice();
        
        //Create a dummy Loan Product
        loan__Loan_Product__c dummyLP = loan.TestHelper.createLoanProduct(dummyOffice,
                            dummyAccount, 
                            curr, 
                            dummyFeeSet);
        dummyLP.loan__Payment_Application_Mode__c = loan.LoanConstants.LOAN_PAYMENT_APPLICATION_CURRENT_DUES;
        
        update dummyLP;
        
        //System.debug(LoggingLevel.ERROR,'LoanProduct in test: ' + dummyLP.Disable_Reserve_Amount_for_Next_Due__c);
        loan__Loan_Purpose__c dummyLoanPurpose = loan.TestHelper.createLoanPurpose();        
        
        Contact c = new Contact(LastName = 'Test');
        insert c;
        
        //Create a dummy Loan Account
        loanAccount = loan.TestHelper.createLoanAccountForContactObj(dummyLP,
                                                    c,
                                                    dummyFeeSet,
                                                    dummyLoanPurpose,
                                                    dummyOffice);
        
        //Create Virtual Card.
        Virtual_Card__c vCard = new Virtual_Card__c();
        vCard.Loan_Account__c = loanAccount.Id;
        vCard.Card_Reference__c = '0RACI_D8GBZeiKne-aQDNwV52';
        
        insert vCard;
        
        loan__Payment_Mode__C pMode = new loan__Payment_Mode__C();
        pMode.Name = 'Refund';
        insert pMode;
        
    }
    
    public static testMethod void runPositiveTests() {
        
        //Create SeedData 
        //createSeedData();
        
        //Run Test
        Test.StartTesT();
            
            Funding_Account_ActivityParser parser = new Funding_Account_ActivityParser();
            parser.fileParser = Blob.valueOf(testString);
            parser.parseFile();
            
        Test.StopTest();
        
        
    
    }
    
    public static testMethod void runPositiveTests1() {
        
        //Create SeedData 
        //createSeedData();
        
        loanAccount = [Select Id,Name from loan__Loan_Account__c limit 1];
        
        //Create Virtual Card.
        Virtual_Card__c vCard = new Virtual_Card__c();
        vCard.Loan_Account__c = loanAccount.Id;
        vCard.Card_Reference__c = '0RACI_D8GBZeiKne-aQDNwV52';
        
        insert vCard;
        
        //Run Test
        Test.StartTesT();
            
            Funding_Account_ActivityParser parser = new Funding_Account_ActivityParser();
            parser.fileParser = Blob.valueOf(testString);
            parser.parseFile();
            
            parser.parseFile();
            
        Test.StopTest();
        
        
    
    }
}