src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>loan__Payment_Mode__c</fullName>
        <description>Payment mode, used to disburse payments back to broker.</description>
        <inlineHelpText>Payment mode, used to disburse payments back to broker.</inlineHelpText>
        <label>Payment Mode</label>
        <picklist>
            <picklistValues>
                <fullName>ACH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/loan__Currency__c.object
<CustomObject>
    <description>Currency</description>
    <label>Currency</label>
    <nameField>
        <label>Currency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Fee__c.object
<CustomObject>
    <description>Fee</description>
    <fields>
        <fullName>loan__Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Currency</description>
        <inlineHelpText>Currency</inlineHelpText>
        <label>Currency</label>
        <referenceTo>loan__Currency__c</referenceTo>
        <relationshipLabel>Fees</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fee</label>
    <nameField>
        <label>Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Fee_Junction__c.object
<CustomObject>
    <fields>
        <fullName>loan__Fee_Set__c</fullName>
        <label>Fee Set</label>
        <referenceTo>loan__Fee_Set__c</referenceTo>
        <relationshipName>Fee_Junction</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>loan__Fee__c</fullName>
        <label>Fee</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>loan__Fee__c.loan__Time_of_charge__c</field>
                <operation>notEqual</operation>
                <value>Pre-Paid Fees</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>loan__Fee__c</referenceTo>
        <relationshipLabel>Fee Set/Fee</relationshipLabel>
        <relationshipName>Fee_Junction</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Fee Set/Fee</label>
    <nameField>
        <displayFormat>FJIP-{0000000000}</displayFormat>
        <label>Fee Junction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fee Set/Fee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/loan__Fee_Set__c.object
<CustomObject>
    <description>A set of fee</description>
    <label>Fee Set</label>
    <nameField>
        <label>Fee Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fee Set</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_Account__c.object
<CustomObject>
    <description>Lending Account</description>
    <fields>
        <fullName>loan__Fee_Set__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Fee Set</description>
        <inlineHelpText>Lookup to associate the fee set on this lending account. Only the fees defined within the fee set can be assessed on this contract.
To create a fee set, Servicing configuration-&gt;Product-&gt;Manage fee set</inlineHelpText>
        <label>Fee Set</label>
        <referenceTo>loan__Fee_Set__c</referenceTo>
        <relationshipName>Loan_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Loan_Purpose__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Loan Purpose</description>
        <inlineHelpText>Loan purpose</inlineHelpText>
        <label>Purpose</label>
        <referenceTo>loan__Loan_Purpose__c</referenceTo>
        <relationshipName>Loan_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Minimum_Due_Amount_On_Billing__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Minimum Bill Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Payment_Application_Mode__c</fullName>
        <description>If the value is Future Dues, Reserve Amount For Next Due will be used for satisfying Bills. Otherwise, Reserve Amount For Next Due will not be used for satisfying Bills.</description>
        <inlineHelpText>Possible values are 
1) Future Dues
2) Current Dues
Future Dues is used when Loan Payments should be used to satisfy future dues.
Current Dues is used when Loan Payments should only be used to satisfy present dues.</inlineHelpText>
        <label>Payment Application Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Future Dues</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Current Dues</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_account_Due_Details__c.object
<CustomObject>
    <description>Invoices/bills for customer loans.</description>
    <fields>
        <fullName>loan__Due_Amt__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Due Amount</description>
        <label>Due Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Due_Date__c</fullName>
        <description>Due date of the due.</description>
        <inlineHelpText>Due Date of the Due</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>loan__Loan_Account__c</fullName>
        <label>Loan Account</label>
        <referenceTo>loan__Loan_Account__c</referenceTo>
        <relationshipName>Dues_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Bills</label>
    <nameField>
        <displayFormat>PCN-{0000000000}</displayFormat>
        <label>Due Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/loan__Loan_Product__c.object
<CustomObject>
    <description>Lending Product Definition1</description>
    <fields>
        <fullName>loan__Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Currency</description>
        <inlineHelpText>Currency</inlineHelpText>
        <label>Currency</label>
        <referenceTo>loan__Currency__c</referenceTo>
        <relationshipName>Loan_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Fee_Set__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fee Set</description>
        <inlineHelpText>Fee set contains the details of all the fees associated with the loan.</inlineHelpText>
        <label>Fee Set</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected Fee Set&apos;s category must be of type &apos;Loan&apos; and it should include at least one fee.</errorMessage>
            <filterItems>
                <field>loan__Fee_Set__c.loan__Fee_Set_Category__c</field>
                <operation>equals</operation>
                <value>Loan</value>
            </filterItems>
            <filterItems>
                <field>loan__Fee_Set__c.loan__Number_of_Fees__c</field>
                <operation>notEqual</operation>
                <value>0</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>loan__Fee_Set__c</referenceTo>
        <relationshipName>Loan_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Payment_Application_Mode__c</fullName>
        <description>If the value is Future Dues, Reserve Amount For Next Due will be used for satisfying Bills. Otherwise, Reserve Amount For Next Due will not be used for satisfying Bills.</description>
        <inlineHelpText>Select Future Dues if the loan payments must be used to satisfy future dues. 
 Select Current Dues if the loan payments must be used to to satisfy present dues.</inlineHelpText>
        <label>Payment Application Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Future Dues</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Current Dues</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Lending Product</label>
    <nameField>
        <label>Loan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lending Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_Purpose__c.object
<CustomObject>
    <description>Loan Purpose</description>
    <label>Loan Purpose</label>
    <nameField>
        <label>Loan Purpose Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Purpose</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__MF_Account__c.object
<CustomObject>
    <label>GL Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Office_Name__c.object
<CustomObject>
    <description>Name of the office</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Payment_Mode__c.object
<CustomObject>
    <label>Payment Mode</label>
    <nameField>
        <label>Payment Mode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Mode</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Virtual_Card__c.object
<CustomObject>
    <fields>
        <fullName>Card_Reference__c</fullName>
        <label>Card Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_Account__c</fullName>
        <label>CL Contract</label>
        <referenceTo>loan__Loan_Account__c</referenceTo>
        <relationshipLabel>Virtual Cards</relationshipLabel>
        <relationshipName>Virtual_Cards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Virtual Card</label>
    <nameField>
        <label>Virtual Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Virtual Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestBillsTriggerCustomhandler.cls
@isTest
public class TestBillsTriggerCustomhandler {
    private static loan__Loan_Account__c loanAccount;
    
    @testSetup static void createSeedData() {
        System.debug(LoggingLevel.eRROR,' running test data ');
        loan.TestHelper.createSeedDataForTesting();
        
        loan__Currency__c curr = loan.TestHelper.createCurrency();
        //Create a dummy MF_Account
        loan__MF_Account__c dummyAccount = loan.TestHelper.createMFAccount('XXXAccountForTest','10000 - ASSETS');
        loan__MF_Account__c dummyIncAccount = loan.TestHelper.createMFAccount('XXXIncAccountForTest','30000 - INCOME');
        
        //Create a Fee Set
        loan__Fee__c dummyFee = loan.TestHelper.createFee(curr,dummyIncAccount ,dummyAccount);                                    
        loan__Fee_Set__c dummyFeeSet = loan.TestHelper.createFeeSet();
        loan__Fee_Junction__c dummyFeeJunction = loan.TestHelper.createFeeJunction(dummyFee,dummyFeeSet);
        
        loan__Office_Name__c dummyOffice = loan.TestHelper.createOffice();
        
        //Create a dummy Loan Product
        loan__Loan_Product__c dummyLP = loan.TestHelper.createLoanProduct(dummyOffice,
                            dummyAccount, 
                            curr, 
                            dummyFeeSet);
        dummyLP.loan__Payment_Application_Mode__c = loan.LoanConstants.LOAN_PAYMENT_APPLICATION_CURRENT_DUES;
        
        update dummyLP;
        
        //System.debug(LoggingLevel.ERROR,'LoanProduct in test: ' + dummyLP.Disable_Reserve_Amount_for_Next_Due__c);
        loan__Loan_Purpose__c dummyLoanPurpose = loan.TestHelper.createLoanPurpose();        
        
        Contact c = new Contact(LastName = 'Test');
        insert c;
        
        //Create a dummy Loan Account
        loanAccount = loan.TestHelper.createLocAccountForContactObj(dummyLP,
                                                    c,
                                                    dummyFeeSet,
                                                    dummyLoanPurpose,
                                                    dummyOffice);
        
        
        
        //Create Virtual Card.
        Virtual_Card__c vCard = new Virtual_Card__c();
        vCard.Loan_Account__c = loanAccount.Id;
        vCard.Card_Reference__c = '0RACI_D8GBZeiKne-aQDNwV52';
        
        insert vCard;
        
        loan__Payment_Mode__C pMode = new loan__Payment_Mode__C();
        pMode.Name = 'Refund';
        insert pMode;
        
        
        
    }
    
    public static testMethod void runNegativeTests() {
        RecordType rt = [Select Id,Name 
                                    From RecordType Where DeveloperName = 'Line_Of_Credit_Record_Type' 
                                    AND sObjectType = 'loan__Loan_Account__c'];
        System.debug(LoggingLevel.ERROR,' Record Type '+rt+' '+loanAccount);    
        
        loanAccount = [Select Id,Name,RecordTypeId,loan__Minimum_Due_Amount_On_Billing__c from loan__Loan_Account__c limit 1];                        
        loanAccount.RecordTypeId = rt.Id;
        loanAccount.loan__Minimum_Due_Amount_On_Billing__c = 10;
        update loanAccount;
        
        Test.startTest();
            loan__Loan_account_Due_Details__c due = new loan__Loan_account_Due_Details__c();
            due.loan__Loan_Account__c = loanAccount.Id;
            due.loan__Due_Amt__c = 50;
            due.loan__Due_Date__c = Date.today();
            
            insert due;
            
        Test.stopTest();
    
    }
    
    public static testMethod void runPositiveTests() {
        RecordType rt = [Select Id,Name 
                                    From RecordType Where DeveloperName = 'Line_Of_Credit_Record_Type' 
                                    AND sObjectType = 'loan__Loan_Account__c'];
        System.debug(LoggingLevel.ERROR,' Record Type '+rt+' '+loanAccount);    
        
        loanAccount = [Select Id,Name,RecordTypeId,loan__Minimum_Due_Amount_On_Billing__c from loan__Loan_Account__c limit 1];                        
        loanAccount.RecordTypeId = rt.Id;
        loanAccount.loan__Minimum_Due_Amount_On_Billing__c = 25;
        update loanAccount;
        
        Test.startTest();
            loan__Loan_account_Due_Details__c due = new loan__Loan_account_Due_Details__c();
            due.loan__Loan_Account__c = loanAccount.Id;
            due.loan__Due_Amt__c = 50;
            due.loan__Due_Date__c = Date.today();
            
            insert due;
            
        Test.stopTest();
    
    }

}