src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_ID__c</fullName>
        <displayFormat>CID-{00000000}</displayFormat>
        <label>Contact ID</label>
        <type>AutoNumber</type>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/loan__Charge__c.object
<CustomObject>
    <description>Charge is something that is applied.</description>
    <fields>
        <fullName>loan__Date__c</fullName>
        <inlineHelpText>This is the date the charge was incurred.</inlineHelpText>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>loan__Fee__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>The associated Fee. The Fee object is used in case of automatic application of a charge. For example, the late fees is charged automatically on a loan.</inlineHelpText>
        <label>Fee</label>
        <referenceTo>loan__Fee__c</referenceTo>
        <relationshipLabel>Charges</relationshipLabel>
        <relationshipName>Charges</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Interest_Rate__c</fullName>
        <inlineHelpText>This is the interest rate to be applied on the charge (if applicable)</inlineHelpText>
        <label>Interest Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>loan__Loan_Account__c</fullName>
        <inlineHelpText>The associated loan.</inlineHelpText>
        <label>Loan Account</label>
        <referenceTo>loan__Loan_Account__c</referenceTo>
        <relationshipLabel>Charges</relationshipLabel>
        <relationshipName>Charges</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>loan__Original_Amount__c</fullName>
        <inlineHelpText>The original amount of the charge.</inlineHelpText>
        <label>Original Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <label>Charge</label>
    <nameField>
        <displayFormat>CHG-{00000000}</displayFormat>
        <label>Charge Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/loan__Fee__c.object
<CustomObject>
    <description>Fee</description>
    <fields>
        <fullName>loan__Amount__c</fullName>
        <description>Number or % 
Amount, is a flat amount. For other fee calculation methods, this is a % amount.</description>
        <inlineHelpText>Number or % 
Amount, is a flat amount. For other fee calculation methods, this is a % amount.</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Fee_Calculation_Method__c</fullName>
        <description>Fee Calculation Method</description>
        <inlineHelpText>Fee Calculation Method</inlineHelpText>
        <label>Fee Calculation Method</label>
        <picklist>
            <controllingField>loan__Fee_Category__c</controllingField>
            <picklistValues>
                <fullName>Amount calculated as % of loan amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amount calculated as % of loan payoff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amount calculated as % of payment amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amount calculated as % of principal balance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Custom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amount calculated as % of disbursement amount</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>loan__Interest_Rate__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Interest Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Maximum_Amount__c</fullName>
        <label>Maximum Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Minimum_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Minimum Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Time_of_charge__c</fullName>
        <description>Time of charge</description>
        <inlineHelpText>Time of charge</inlineHelpText>
        <label>Time of charge</label>
        <picklist>
            <controllingField>loan__Fee_Category__c</controllingField>
            <picklistValues>
                <fullName>Late Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pay-Off Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSF Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wire Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Periodic Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Amortized Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Time of Disbursement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Paid Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Esker</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Fee</label>
    <nameField>
        <label>Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Fee_Junction__c.object
<CustomObject>
    <fields>
        <fullName>loan__Fee_Set__c</fullName>
        <label>Fee Set</label>
        <referenceTo>loan__Fee_Set__c</referenceTo>
        <relationshipName>Fee_Junction</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>loan__Fee__c</fullName>
        <label>Fee</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>loan__Fee__c.loan__Time_of_charge__c</field>
                <operation>notEqual</operation>
                <value>Pre-Paid Fees</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>loan__Fee__c</referenceTo>
        <relationshipLabel>Fee Set/Fee</relationshipLabel>
        <relationshipName>Fee_Junction</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Fee Set/Fee</label>
    <nameField>
        <displayFormat>FJIP-{0000000000}</displayFormat>
        <label>Fee Junction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fee Set/Fee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/loan__Fee_Set__c.object
<CustomObject>
    <description>A set of fee</description>
    <label>Fee Set</label>
    <nameField>
        <label>Fee Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fee Set</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_Account__c.object
<CustomObject>
    <description>Lending Account</description>
    <fields>
        <fullName>loan__Fee_Set__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Fee Set</description>
        <inlineHelpText>Lookup to associate the fee set on this lending account. Only the fees defined within the fee set can be assessed on this contract.
To create a fee set, Servicing configuration-&gt;Product-&gt;Manage fee set</inlineHelpText>
        <label>Fee Set</label>
        <referenceTo>loan__Fee_Set__c</referenceTo>
        <relationshipName>Loan_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Interest_Rate__c</fullName>
        <description>Interest Rate</description>
        <inlineHelpText>Rate of Interest for the loan.</inlineHelpText>
        <label>Current Interest Rate</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>loan__Pay_Off_Amount_As_Of_Today__c</fullName>
        <defaultValue>0.0</defaultValue>
        <description>Tells the pay off amount for this account as of today</description>
        <inlineHelpText>Tells the pay off amount for this account as of today</inlineHelpText>
        <label>Today&apos;s Payoff</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Principal_Remaining__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Principal/Advance Remaining</description>
        <inlineHelpText>Unpaid Principal/advance balance on the loan account.</inlineHelpText>
        <label>Principal/Advance Remaining</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Search__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Search</relationshipLabel>
        <relationshipName>Search</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Date__c</fullName>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>loan__Loan_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan Account</label>
        <referenceTo>loan__Loan_Account__c</referenceTo>
        <relationshipLabel>Search</relationshipLabel>
        <relationshipName>Search</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Search</label>
    <nameField>
        <label>Saved Search Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Search</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EskerUIController.cls
global class EskerUIController {
    public loan__Search__c searchObj{get;set;}
    public Blob fileContent{get;set;}
    public String fileName { get; set;}
    public String contactId {get; set;}
    
    public Contact con{get;set;}
    public boolean showLookup{get;set;}
    
    private Id loanAccountID;
    private loan__Loan_Account__c lA;
    private Date systemDate;
    
    public EskerUIController(ApexPages.StandardController controller) {
    
        searchObj = new loan__Search__c();
        con = (Contact) controller.getRecord();
        showLookup = (con.Id == null) ? true : false;
        
        systemDate = (new loan.GlobalLoanUtilFacade()).getCurrentSystemDate();
        
        if(!showLookup) {
            contactId = con.Id;
            con = getContact(con.Id);
        }
        
        loanAccountID = ApexPages.currentPage().getParameters().get('loanAccountId');
    }
    
    private Contact getContact(Id conId){
        Contact con = [Select Id,Name,
                          MailingStreet,
                          MailingCity,
                          MailingCountry,
                          MailingState,
                          MailingPostalCode,
                          Contact_ID__c,
                          Email
                   From Contact
                   Where Id =: conID];
        return con;
    }
    
    private loan__Fee__c getEskerFee(Id loanID) {
        loan__Fee__c retVal;
        
        //Get loan Fee set.
        lA = [Select Id,Name,
                   loan__Fee_Set__c,
                   loan__Principal_Remaining__c,
                   loan__Pay_off_Amount_As_Of_today__c
             from loan__Loan_Account__c
             Where Id =: loanId];
        
        //Get Esker Fee.                             
        if(lA.loan__Fee_Set__c != null) {
            List<loan__Fee_Junction__c> feeJunction = [Select Id,Name,
                                                          loan__fee__r.Id,
                                                          loan__fee__r.Name,
                                                          loan__fee__r.loan__Minimum_Amount__c,
                                                          loan__fee__r.loan__Maximum_Amount__c,
                                                          loan__fee__r.loan__amount__c,
                                                          loan__fee__r.loan__Fee_Calculation_Method__c,
                                                          loan__fee_Set__c
                                                        From loan__Fee_Junction__c
                                                        Where loan__fee_set__c =: la.loan__fee_Set__c
                                                        and loan__Fee__r.loan__Time_Of_Charge__c = 'Esker']; 
                                                            
            if(!feeJunction.isEmpty()){
                retVal = feeJunction[0].loan__Fee__r;
            }
        }
        
        return retVal;
    }
    
    global PageReference uploadMisc() {
        if(contactId == null
            && searchObj.Contact__c != null){
            con = getContact(searchObj.Contact__c);
  
        }
        
        if(String.isEmpty(con.MailingStreet)
            || String.isEmpty(con.MailingCity)
            || String.isEmpty(con.MailingCountry)
            || String.isEmpty(con.MailingPostalCode)
            || String.isEmpty(con.MailingState)) {
            
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,' Mailing address for this customer seems incorrect. Please check Mailing address information for customer.'));
            return null;
        }
        
        try{
            WSSnailMail sendMailWs;
            String result;
            
            if(!Test.isRunningTest()){
                sendMailWs = new WSSnailMail();
                result = sendMailWs.sendMail(fileContent, con,fileName);
            }
            
            //Apply Charge on Contract
            loan__Charge__c charge;
            if(loanAccountId != null) {
                //Get Esker Fee
                loan__Fee__c eskerFee = getEskerFee(loanAccountId);
                if(eskerFee != null) {
                
                    charge = new loan__Charge__c();
                    charge.loan__Loan_Account__c = loanAccountId;
                    charge.loan__Fee__c = eskerFee.Id;
                    charge.loan__Original_Amount__c = loan.FeeUtil.computeFee(eskerFee,lA);
                    charge.loan__Interest_Rate__c  = 0;
                    charge.loan__Date__c = systemDate;
                    insert charge;            
                }
            }    
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, result));
            
        }catch(Exception e){
             ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage() + ' From line '+e.getLinenumber()));
             return null;
        }
        
        return new PageReference('/'+getNavigationId());
        
    }
    
    private Id getNavigationId(){
        if(loanAccountId != null){
            return loanAccountId;
        }else{
            return con.Id;
        }
    }
}