src/objects/Datacash_Config__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Server_Url__c</fullName>
        <label>Server Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Datacash Configuration</label>
</CustomObject>

src/objects/loan__Bank_Account__c.object
<CustomObject>
    <fields>
        <fullName>Bank_Card_Details__c</fullName>
        <label>Card Number</label>
        <length>20</length>
        <maskChar>X</maskChar>
        <maskType>creditCard</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>CVV__c</fullName>
        <label>Security Code</label>
        <length>3</length>
        <maskChar>X</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Expiry_Month__c</fullName>
        <label>Expiry Month</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expiry_Year__c</fullName>
        <label>Expiry Year</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>loan__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Bank Accounts</relationshipLabel>
        <relationshipName>Bank_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bank Account</label>
    <nameField>
        <displayFormat>BA-{00000}</displayFormat>
        <label>Bank Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Batch_Process_Log__c.object
<CustomObject>
    <fields>
        <fullName>loan__Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>loan__Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Batch Process Log</label>
    <nameField>
        <label>Apex Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Process Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_Account__c.object
<CustomObject>
    <description>Lending Account</description>
    <fields>
        <fullName>loan__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Please choose a contact, which will be associated as a customer on this lending account. 
You can create a new contact, from the lookup window by clicking on new or select the existing contact from the lookup.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Loan_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_Payment_Transaction__c.object
<CustomObject>
    <description>Loan Payment Transaction</description>
    <fields>
        <fullName>Datacash_Reference__c</fullName>
        <label>Datacash Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Merchant_Reference__c</fullName>
        <label>Merchant Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Regular</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Retry</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>loan__Cleared__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if this loan payment transaction is supervised or not.</description>
        <inlineHelpText>Indicates if this loan payment transaction is supervised or not.</inlineHelpText>
        <label>Cleared</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>loan__Loan_Account__c</fullName>
        <description>Loan Account</description>
        <inlineHelpText>Loan Account</inlineHelpText>
        <label>Loan Account</label>
        <referenceTo>loan__Loan_Account__c</referenceTo>
        <relationshipLabel>Loan Payment Transactions</relationshipLabel>
        <relationshipName>Loan_Payment_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>loan__Transaction_Amount__c</fullName>
        <description>Transaction Amount</description>
        <inlineHelpText>This is the sum of Interest, Principal and Fees</inlineHelpText>
        <label>Transaction Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Loan Payment Transaction</label>
    <nameField>
        <displayFormat>LPT-{000000000}</displayFormat>
        <label>Loan Payment Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Payment Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/loan__Repayment_Transaction_Adjustment__c.object
<CustomObject>
    <description>Repayment Transaction Adjustment Object</description>
    <fields>
        <fullName>Attempt_Retry__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Should System attempt retry for this ? Retry attempt is made after 7 days.</inlineHelpText>
        <label>Attempt Retry</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Process_Refund__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Process Refund</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>loan__Adjusted_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Adjusted Amount (+ve or -ve). This is not yet implemented. 
Reversal Txn will reverse the master payment transaction&apos;s full amount.</description>
        <inlineHelpText>Adjusted Amount (+ve or -ve). This is not yet implemented. 
Reversal Txn will reverse the master payment transaction&apos;s full amount.</inlineHelpText>
        <label>Adjusted Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Adjustment_Txn_Date__c</fullName>
        <defaultValue>$User.loan__Current_Branch_s_System_Date__c</defaultValue>
        <description>Adjustment Txn Date</description>
        <inlineHelpText>Adjustment Txn Date</inlineHelpText>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>loan__Cleared__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cleared</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>loan__Loan_Payment_Transaction__c</fullName>
        <description>Loan Payment Transaction</description>
        <inlineHelpText>Loan Payment Transaction</inlineHelpText>
        <label>Loan Payment Transaction</label>
        <referenceTo>loan__Loan_Payment_Transaction__c</referenceTo>
        <relationshipName>Repayment_Transaction_Adjustment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Repayment Transaction Reversal</label>
    <nameField>
        <displayFormat>RTA-{0000000000}</displayFormat>
        <label>Repayment Transaction Adjustment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Transaction Reversal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/loan__Transaction_Approval_Config__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Payment_Retry_Interval__c</fullName>
        <label>Payment Retry Interval</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Transaction Approval Config</label>
</CustomObject>

src/objects/Payment_Retry__c.object
<CustomObject>
    <fields>
        <fullName>CL_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CL Contract</label>
        <referenceTo>loan__Loan_Account__c</referenceTo>
        <relationshipLabel>Payment Retry</relationshipLabel>
        <relationshipName>Payment_Retry</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Debit_amount__c</fullName>
        <label>Debit amount</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <label>Payment Retry</label>
    <nameField>
        <label>Payment Retry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Retry</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CustomRepaymentReversalTriggerHandler.cls
public class CustomRepaymentReversalTriggerHandler {
    private List<loan__Repayment_Transaction_Adjustment__c> txnList;
    private List<loan__Repayment_Transaction_Adjustment__c> refundProcess;
    private Map<Id,loan__Repayment_Transaction_Adjustment__c> oldMap;
    
    private loan__Transaction_Approval_Config__c approvalConfig;
    
    private Set<Id> txnIds = new SeT<Id>();
    private Set<ID> borrowerIDs = new Set<Id>();
    private Map<Id,loan__Repayment_Transaction_Adjustment__c> requeriedMap;
    private Map<Id,loan__Loan_Payment_Transaction__c> paymentMap;
    private List<loan__Loan_Payment_Transaction__c> paymentList;
    private Map<Id,loan__Bank_Account__c> borrowerCardDetailsMap;
    
    private List<Payment_Retry__c> recsToCreate;
    private Datacash_Config__c config;
    
    public CustomRepaymentReversalTriggerHandler(List<loan__Repayment_Transaction_Adjustment__c> txnList,
                                          Map<Id,loan__Repayment_Transaction_Adjustment__c> oldMap) {
    
        this.txnList = txnList;
        this.oldMap = oldMap;
        
        recsToCreate = new List<Payment_Retry__c>();
        refundProcess = new List<loan__Repayment_Transaction_Adjustment__c>();
        paymentMap = new Map<Id,loan__Loan_Payment_Transaction__c>();
        borrowerCardDetailsMap = new Map<Id,loan__Bank_Account__c>();
        paymentList = new List<loan__Loan_Payment_Transaction__c>();
        
        approvalConfig = loan__Transaction_Approval_Config__c.getOrgDefaults();
        
        //get custom setting details to Send payment to Datacash
        config = Datacash_Config__c.getOrgDefaults();   
        
        //Get Txn IDs for requery.
        for(loan__Repayment_Transaction_Adjustment__c txn : txnList) {
            txnIDs.add(txn.Id);
            
        }
        
        requeriedMap = new Map<Id,loan__Repayment_Transaction_Adjustment__c>([Select Id,Name,
                                                                                     loan__Loan_Payment_Transaction__c,
                                                                                     loan__Loan_Payment_Transaction__r.loan__Loan_Account__r.loan__Contact__c,
                                                                                     loan__Loan_Payment_Transaction__r.loan__Transaction_Amount__c,
                                                                                     loan__Loan_Payment_Transaction__r.loan__Loan_Account__c,
                                                                                     loan__Loan_Payment_Transaction__r.Datacash_Reference__c,
                                                                                     loan__Loan_Payment_Transaction__r.Merchant_Reference__c,
                                                                                     loan__Loan_Payment_Transaction__r.Payment_Type__c
                                                                              From loan__Repayment_Transaction_Adjustment__c
                                                                              Where Id in :txnIDs]);
                                                                              
        /*Prepare map for Reversals vs its lpt.
        for(loan__Repayment_Transaction_Adjustment__c reqRec : requeriedMap.values()) {
            borrowerIds.add(reqRec.loan__Loan_Payment_Transaction__r.loan__Loan_Account__r.loan__Contact__c);
            paymentMap.put(reqRec.Id,reqRec.loan__Loan_Payment_Transaction__r);
        }
        
        //Query borroers & its bank details.
        List<Contact> borrowers = [Select Id,Name,
                                          (Select Id,Name,
                                                  Bank_Card_Details__c,
                                                  Expiry_Month__c,
                                                  Expiry_Year__c,
                                                  CVV__c,
                                                  loan__Active__c
                                           from loan__Bank_Accounts__r
                                           Where loan__Active__c = true)
                                   From Contact
                                   Where Id in :borrowerIds];
        
        for(Contact c : borrowers) {
            if(c.loan__Bank_Accounts__r != null && !c.loan__Bank_Accounts__r.isEmpty()) {
                borrowerCardDetailsMap.put(c.Id,c.loan__Bank_Accounts__r[0]);
            }
        }*/
    }
    
    public void onAfterUpdate() {
        loan__Repayment_Transaction_Adjustment__c beforeUpdate;
        
        BorrowerImpl impl = new BorrowerImpl();
         
        for(loan__Repayment_Transaction_Adjustment__c adjTxn : txnList) { 
            beforeUpdate = oldMap.get(adjTxn.Id);
            
            if(beforeUpdate.loan__cleared__c == false 
                && adjTxn.loan__cleared__c == true 
                && adjTxn.Attempt_Retry__c
                && requeriedMap.get(adjTxn.Id).loan__Loan_Payment_Transaction__r.Payment_Type__c != 'Retry') {
               
               System.debug(LoggingLEvel.ERROR,' Creating txn ');
                
               recsToCreate.add(getPaymentRetryOrder(adjTxn));       
            
            }
        }
        
        //Create Retry Transaction Order for Loans.
        SavePoint sp = Database.setSavePoint();
        try {
            insert recsToCreate;
            System.debug(LoggingLevel.ERROR,' Updated Successfully');
        }catch(Exception e){
            Database.rollback(sp);
            loan__Batch_Process_Log__c errorLog = new loan__Batch_Process_Log__c();
            errorLog.loan__Message__c = 'Error : LoanPaymentReversalTrigger: '+e.getMessage()+' from line '+e.getLineNumber();
            errorLog.loan__Date__c = Date.newInstance(System.now().year(),System.now().month(),System.now().day());
            
            insert errorLog;
        }
    }
    
    /*
    
    @future
    public static void processDatacashRefunds() {
        loan__Bank_Account__c activeCard;
        Datacash_Config__c config = Datacash_Config__c.getOrgDefaults();  
        
        for(loan__Repayment_Transaction_Adjustment__c adjTxn : tList) {
            if(adjTxn.Process_Refund__c){ 
                System.debug(LoggingLevel.ERROR,' Processing Refund ');
                activeCard = borrowerCardDetailsMap.get(requeriedMap.get(adjTxn.Id)
                                                                    .loan__Loan_Payment_Transaction__r
                                                                    .loan__Loan_Account__r
                                                                    .loan__Contact__c);
                
                if(activeCard != null) {
                   //Send to Datacash.
                    PaymentTransactionResponse payResponse = impl.sendPaymentToDataCashRefund(config.Server_Url__c,
                                                                                           config.Username__c,
                                                                                           config.password__c,
                                                                                           activeCard,
                                                                                           paymentMap.get(adjTxn.Id));
                    
                    //If Response is success, 
                    if(payResponse.successMessage.equals('SUCCESS')) {
                        System.debug(LoggingLevel.ERROR,' Refund Successful.');
                        paymentList.add(payResponse.lpt);
                    }else {
                        //Datacash refund unsuccessful. [ask TF].
                    }                                                                
                }//end second if.
                
            }//end first if
            
        }//end for loop.
        
        if(!paymentList.isEmpty()) {
            update paymentList;
        }    
    }*/
    
    private Payment_Retry__c getPaymentRetryOrder(loan__Repayment_Transaction_Adjustment__c adj) {
        
        Decimal interval = (approvalConfig.Payment_Retry_Interval__c == null) ? 7 : approvalConfig.Payment_Retry_Interval__c;
    
        Payment_Retry__c retVal = new Payment_Retry__c();
        retVal.Transaction_Date__c = adj.loan__Adjustment_Txn_Date__c.addDays((Integer)interval);
        retVal.Debit_amount__c = (adj.loan__Adjusted_Amount__c == 0 || adj.loan__Adjusted_Amount__c == null) 
                                ? requeriedMap.get(adj.Id).loan__Loan_Payment_Transaction__r.loan__Transaction_Amount__c
                                : adj.loan__Adjusted_Amount__c;
        retVal.CL_Contract__c = requeriedMap.get(adj.Id).loan__Loan_Payment_Transaction__r.loan__Loan_Account__c;
        
        return retVal;
    }
    
}