src/objects/Insight_Header_Trailer__c.object
<CustomObject>
    <fields>
        <fullName>Company_ID__c</fullName>
        <label>Company ID</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Type__c</fullName>
        <label>Company Type</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Code__c</fullName>
        <label>Record Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Insight Header Trailer</label>
    <nameField>
        <displayFormat>IH-{000000}</displayFormat>
        <label>Insight_Header__c Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insight Header Trailer</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_Account__c.object
<CustomObject>
    <description>Lending Account</description>
    <fields>
        <fullName>loan__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Please choose a contact, which will be associated as a customer on this lending account. 
You can create a new contact, from the lookup window by clicking on new or select the existing contact from the lookup.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Loan_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Disbursal_Date__c</fullName>
        <description>Contract Date on the Loan account, this will be updated at the time of funding with the Expected Disbursal Date.</description>
        <inlineHelpText>Contract date on the loan. This will be updated at the time of funding with the expected disbursal date.</inlineHelpText>
        <label>Contract Date</label>
        <type>Date</type>
    </fields>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OI_Entry_Record__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Consent_To_Data_Sharing__c</fullName>
        <description>Y or N</description>
        <label>Consent To Data Sharing</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Account_Holders__c</fullName>
        <label>Number of Account Holders</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OI_Account_Number__c</fullName>
        <label>OI_Account_Number</label>
        <length>19</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OI_Account_Type__c</fullName>
        <label>OI_Account_Type</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OI_Address_Line1__c</fullName>
        <label>OI_Address_Line1</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OI_Address_Line2__c</fullName>
        <label>OI_Address_Line2</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OI_Address_Line3__c</fullName>
        <label>OI_Address_Line3</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OI_Address_Line4__c</fullName>
        <label>OI_Address_Line4</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OI_Address_Line5__c</fullName>
        <label>OI_Address_Line5</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OI_Birth_Date__c</fullName>
        <label>OI_Birth_Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OI_Date_of_Application__c</fullName>
        <label>OI Date of Application</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OI_Declared_Salary__c</fullName>
        <label>OI_Declared_Salary</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OI_Forename__c</fullName>
        <label>OI_Forename</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OI_Other_Name__c</fullName>
        <label>OI_Other_Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OI_Postcode__c</fullName>
        <label>OI_Postcode</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OI_Salary_Verified__c</fullName>
        <description>Y or N</description>
        <label>OI Salary Verified</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OI_Suffix__c</fullName>
        <label>OI_Suffix</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OI_Surname__c</fullName>
        <label>OI_Surname</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OI_Title__c</fullName>
        <label>OI_Title</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Previous_Address_2__c</fullName>
        <label>Previous Address 2</label>
        <length>168</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Previous_Address__c</fullName>
        <label>Previous Address 1</label>
        <length>168</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salary_Net_Gross__c</fullName>
        <description>N = Monthly Net , G = Annual Gross</description>
        <label>Salary (Net/Gross)</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <label>OI Entry Record</label>
    <nameField>
        <label>Custom Object Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OI Entry Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SHARE__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Company_ID__c</fullName>
        <label>Company ID</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Type__c</fullName>
        <label>Company Type</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Code__c</fullName>
        <label>Record Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>SHARE</label>
</CustomObject>

src/classes/OIFormatGen.cls
public class OIFormatGen extends loan.FileGenerator {
    private Date systemDate;
    private loan.GlobalLoanUtilFacade facade;
    private SHARE__c shareParams;
    
    public override String getSimpleFileName() {
        return 'OI_Report'+'_'+System.now();
    }

    public OIFormatGen(){
        super();
        
        facade = new loan.GlobalLoanUtilFacade();
        systemDate = facade.getCurrentSystemDate();
        
    }
    
    private OI_Entry_Record__c generateEntryDetailRecord(loan__Loan_Account__c loan){
        OI_Entry_Record__c rec = new OI_Entry_Record__c();
        
        //1. Reference Number - Loan Account Number - 19
        rec.OI_Account_Number__c = loan.Name;
        
        //2. Name - Contact Name - 120
        rec.OI_Title__c = (loan.loan__Contact__r.salutation != null) ? loan.loan__Contact__r.salutation : '';
        rec.OI_Forename__c = loan.loan__Contact__r.FirstName;
        rec.OI_Other_Name__c = (loan.loan__Contact__r.MiddleName != null) ? loan.loan__Contact__r.MiddleName : '';
        rec.OI_Surname__c = loan.loan__Contact__r.LastName;
        rec.OI_Suffix__c = (loan.loan__Contact__r.suffix != null) ? loan.loan__Contact__r.suffix : '';
        
        //3. Full Address - Mailing Address on Contact. - 168
        rec.OI_Address_Line1__c = loan.loan__Contact__r.MailingStreet;
        rec.OI_Address_Line2__c = loan.loan__Contact__r.MailingCity;
        rec.OI_Address_Line3__c = loan.loan__Contact__r.MailingState;
        rec.OI_Address_Line4__c = '';
        rec.OI_Address_Line5__c = '';
        rec.OI_Postcode__c = loan.loan__Contact__r.MailingPostalCode;
        
        //4. Previous Address - Not reporting. blank. - 168
        rec.Previous_Address__c = '';
        
        //5. Previous Address2 - Not Reporting. - 168
        rec.Previous_Address_2__c = '';
        
        //6. Date of Birth - Contact DOB - 8
        rec.OI_Birth_Date__c = loan.loan__Contact__r.Birthdate;
        
        //7. Declared Amount - Signed amount to nearest rounded pound. - 9
        rec.OI_Declared_Salary__c = 100000000;
        
        //8. Salary Net/Gross - 1
        rec.Salary_Net_Gross__c = 'G';
        
        //9. Account Type - cc - 2
        rec.OI_Account_Type__c = 'CC';
        
        //10. Consent To Data Sharing - Yes/No - 1
        rec.Consent_To_Data_Sharing__c = 'Y';
        
        //11. Number of Account Holders - no. of applicants - 2
        rec.Number_of_Account_Holders__c = 1;
        
        //12. Date of application - YYYYMMDD - 8
        rec.OI_Date_of_Application__c = loan.loan__Disbursal_Date__c;
        
        //13. Salary Verified - Y/N - 1
        rec.OI_Salary_Verified__c = 'Y';
        
        
        System.debug(LoggingLevel.ERROR,' Returning row '+rec);
        return rec;
    }
    
    public override List<String> getEntries(loan.TransactionSweepToACHState state, List<SObject> scope) {
        System.debug(loggingLevel.Error,'----:'+'inside entries');
        
        List<String> retVal = new List<String>();
        List<loan__Loan_Account__c> loans = (List<loan__Loan_Account__c>)scope;
        List<SObject> objects = new List<SObject>();
        
        for(loan__Loan_Account__c loan : loans){
            
            system.debug(loggingLevel.Error,'----:'+'inside entries for loop');
            addToValidScope(loan);
            objects.add(generateEntryDetailRecord(loan));           
            
        }
        
        filegen.CreateSegments segments = new filegen.CreateSegments(objects);
        System.debug(LoggingLevel.ERROR,' Segment '+segments);
        retVal = segments.retString();
        
        System.debug(' Ret Val '+retVal);
        for(String line : retVal){
            line = line+'\n';
            addEntry(line);
        }
        System.debug(LoggingLevel.ERROR,' Finished Entries ');
        return retVal;
    }
    
    public override String getHeader(loan.TransactionSweepToACHState state, List<SObject> scope) {
        String header = '';
        List<String> retVal = new List<String>();
        
        Insight_Header_Trailer__c headerRec = new Insight_Header_Trailer__c();
        headerRec.Record_Code__c = '';
        headerRec.Company_ID__c = '';
        headerRec.Company_Type__c = '';
                                         
        List<SObject> headerRecs = new List<SObject>();
        headerRecs.add(headerRec);
       
        filegen.CreateSegments segments =new filegen.CreateSegments(headerRecs);
        
        retVal = segments.retString();
        retVal[0] = retVal[0].removeEnd('\r\n');
        
        //Add Filler.
        for(Integer i = 0;i< 497;i++){
            retVal[0] = retVal[0] + ' ';
        }
        header = '';
        return header;
        
    }
    
    public override String getTrailer(loan.TransactionSweepToACHState state, LIST<SObject> scope) {
        String trailer = '';
        List<String> retVal = new List<String>();
        
        Insight_Header_Trailer__c headerRec = new Insight_Header_Trailer__c();
        headerRec.Record_Code__c = '';
        headerRec.Company_ID__c = '';
        headerRec.Company_Type__c = '';
        
        List<SObject> headerRecs = new List<SObject>();
        headerRecs.add(headerRec);
       
        filegen.CreateSegments segments =new filegen.CreateSegments(headerRecs);
        retVal = segments.retString();
        
        trailer = '';
        return trailer;
        //return 'TRAILER';
    }
}