src/objects/loan__Loan_Account__c.object
<CustomObject>
    <description>Lending Account</description>
    <fields>
        <fullName>Current_Status__c</fullName>
        <label>Current Status (Equifax Reporting)</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Q</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>U</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Delinquent_Amount_Snapshot__c</fullName>
        <label>First Delinquency Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Flag__c</fullName>
        <label>Flag</label>
        <picklist>
            <picklistValues>
                <fullName>D</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>G</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>M</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>P</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>I</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>V</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>S</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>loan__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Please choose a contact, which will be associated as a customer on this lending account. 
You can create a new contact, from the lookup window by clicking on new or select the existing contact from the lookup.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Loan_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Credit_Limit__c</fullName>
        <description>Credit Limit for Line of Credit</description>
        <inlineHelpText>This is the contractual maximum advance limit, total advance withdrawn must not exceed this limit.</inlineHelpText>
        <label>Credit Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Disbursal_Date__c</fullName>
        <description>Contract Date on the Loan account, this will be updated at the time of funding with the Expected Disbursal Date.</description>
        <inlineHelpText>Contract date on the loan. This will be updated at the time of funding with the expected disbursal date.</inlineHelpText>
        <label>Contract Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>loan__First_Installment_Date__c</fullName>
        <description>Date of the first installment</description>
        <inlineHelpText>This is the desired start date of the repayment schedule that is provided while creating the loan application.</inlineHelpText>
        <label>First Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>loan__Frequency_of_Loan_Payment__c</fullName>
        <inlineHelpText>This decides the Payment Frequency, below are the supported ones:
Daily
Weekly
Bi-weekly
Semi-Monthly
Monthly
Bi-Monthly  
Quarterly
Semi-Annual
Annual 
Single-Payment</inlineHelpText>
        <label>Payment Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Daily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Bi-Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quarterly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Single-Payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Semi-Monthly-PD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>loan__Last_Payment_Date__c</fullName>
        <description>Date when last payment was received.</description>
        <inlineHelpText>Date when the  last payment was received.</inlineHelpText>
        <label>Last Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>loan__Loan_Status__c</fullName>
        <inlineHelpText>Status of the Account, expected values are :
Pending Approval
Active - Good Standing
Active - Bad Standing
Active - Matured
Approved
Canceled
Closed - Obligations met
Closed- Written Off
Closed - Refinanced
Partial Application</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Partial Application</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active - Good Standing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active - Bad Standing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Obligations met</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed- Written Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Refinanced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active - Matured</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>loan__Metro2_First_Delinquency_Date__c</fullName>
        <inlineHelpText>This will be reported only if the Account Status Code is 61-65, 71, 78, 80, 82-84, 88-89 and 93-97.
This field gets updated only when the status of loan account changes from Active-Good Standing to Active-Bad Standing.</inlineHelpText>
        <label>Date of First Delinquency</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>loan__Number_of_Days_Overdue__c</fullName>
        <inlineHelpText>Number of days for which there has been an overdue on the loan account.</inlineHelpText>
        <label>Days Past Due</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Pay_Off_Amount_As_Of_Today__c</fullName>
        <defaultValue>0.0</defaultValue>
        <description>Tells the pay off amount for this account as of today</description>
        <inlineHelpText>Tells the pay off amount for this account as of today</inlineHelpText>
        <label>Today&apos;s Payoff</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Term_Cur__c</fullName>
        <description>Current Term</description>
        <inlineHelpText>Current loan account term.</inlineHelpText>
        <label>Current Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_Status__c.object
<CustomObject>
    <description>Object for storing Loan Statuses</description>
    <label>Loan Status</label>
    <nameField>
        <label>Loan Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ShareReportingFileGen.cls
global class ShareReportingFileGen implements Schedulable, Database.Batchable<Sobject>,Database.Stateful {
    private String query;
    private static String NAME = 'SHARE FILE GENERATOR JOB';
    private loan.TransactionSweepToACHState state;
    private Date iDate;
    
    global ShareReportingFileGen() {
    
        String NonAllowabledLoanStatuses = '\'' + loan.LoanConstants.LOAN_STATUS_PARTIAL_APPLICATION + '\'' + ',' + 
                                        '\''+ loan.LoanConstants.LOAN_STATUS_PENDING_APPROVAL + '\'' + ',' + 
                                        '\''+ loan.LoanConstants.LOAN_STATUS_APPROVED + '\''+ ',' +
                                        '\''+ loan.LoanConstants.LOAN_STATUS_CANCELED +'\''+ ','+
                                        '\''+ loan.LoanConstants.LOAN_STATUS_CLOSED_RESCHEDULED +'\''+','+
                                        '\''+ loan.LoanConstants.LOAN_STATUS_DISBURSED_TO_LO +'\'';
        
        query = 'Select Id,Name,'+
                        'loan__Contact__r.FirstName,'+
                        'loan__Contact__r.LastName,'+
                        'loan__Contact__r.suffix,'+
                        'loan__Contact__r.MiddleName,'+
                        'loan__Contact__r.salutation,'+
                        'loan__Contact__r.Birthdate,'+
                        'loan__Contact__r.MailingStreet,'+
                        'loan__Contact__r.MailingCity,'+
                        'loan__Contact__r.MailingState,'+
                        'loan__Contact__r.MailingPostalCode,'+
                        'loan__Disbursal_Date__c,'+
                        'loan__Loan_Status__c,'+
                        'loan__Last_Payment_Date__c,'+
                        'loan__Credit_Limit__c,'+
                        'loan__Pay_Off_Amount_As_Of_Today__c,'+
                        'loan__Term_Cur__c,'+
                        'loan__Frequency_of_Loan_Payment__c,'+
                        'loan__Metro2_First_Delinquency_Date__c,'+
                        'Delinquent_Amount_Snapshot__c,'+
                        'loan__Number_of_Days_Overdue__c,'+
                        'loan__First_Installment_Date__c,'+
                        'Flag__c,'+
                        'Current_Status__c'+
                ' From loan__Loan_Account__c '+
                ' WHERE loan__Loan_Status__c NOT IN ('+ NonAllowabledLoanStatuses +')';
                
        state = new loan.TransactionSweepToACHState();
    }
    
    global void execute(SchedulableContext sc) {
        ShareReportingFileGen j = new ShareReportingFileGen();
        Database.executeBatch(j);
    }
    
    global Database.Querylocator start(Database.BatchableContext bc) {
        System.debug(LoggingLevel.ERROR,' Query '+query);
        return Database.getQueryLocator(query);
    } // do nothing
    
    global void execute(Database.BatchableContext bc, List<sObject> scope) {
        if (scope.size() == 0) {
            return;
        }
        try {
            loan.FileGenerator filegen = new ShareInsightFormatGen();
            filegen.setScope(scope);
            filegen.createLines(state);
            String filename = filegen.writeFile(state);
            List<SObject> validScope = filegen.getValidScope();
            
        } catch (Exception e) {
            throw new GeneralException(e.getMessage()+' From line '+e.getLinenumber());
        }
    }
    
    global void finish(Database.BatchableContext bc) {
        
    }

}