src/objects/loan__Loan_Account__c.object
<CustomObject>
    <description>Lending Account</description>
    <fields>
        <fullName>loan__Payment_Application_Mode__c</fullName>
        <description>If the value is Future Dues, Reserve Amount For Next Due will be used for satisfying Bills. Otherwise, Reserve Amount For Next Due will not be used for satisfying Bills.</description>
        <inlineHelpText>Possible values are 
1) Future Dues
2) Current Dues
Future Dues is used when Loan Payments should be used to satisfy future dues.
Current Dues is used when Loan Payments should only be used to satisfy present dues.</inlineHelpText>
        <label>Payment Application Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Future Dues</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Current Dues</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_Payment_Transaction__c.object
<CustomObject>
    <description>Loan Payment Transaction</description>
    <fields>
        <fullName>loan__Cleared__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if this loan payment transaction is supervised or not.</description>
        <inlineHelpText>Indicates if this loan payment transaction is supervised or not.</inlineHelpText>
        <label>Cleared</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>loan__Loan_Account__c</fullName>
        <description>Loan Account</description>
        <inlineHelpText>Loan Account</inlineHelpText>
        <label>Loan Account</label>
        <referenceTo>loan__Loan_Account__c</referenceTo>
        <relationshipLabel>Loan Payment Transactions</relationshipLabel>
        <relationshipName>Loan_Payment_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>loan__Payment_Application_Mode__c</fullName>
        <description>If the value is Future Dues, Reserve Amount For Next Due will be used for satisfying Bills. Otherwise, Reserve Amount For Next Due will not be used for satisfying Bills.</description>
        <inlineHelpText>Possible values are 
1) Future Dues 
2) Current Dues 
Future Dues is used when Loan Payments should be used to satisfy future dues. 
Current Dues is used when Loan Payments should only be used to satisfy present dues.</inlineHelpText>
        <label>Payment Application Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Future Dues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current Dues</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>loan__Payment_Mode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Mode</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>loan__Payment_Mode__c.Name</field>
                <operation>notEqual</operation>
                <value>Internal Transfer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>loan__Payment_Mode__c</referenceTo>
        <relationshipLabel>Loan Payment Transactions</relationshipLabel>
        <relationshipName>Loan_Payment_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Transaction_Amount__c</fullName>
        <description>Transaction Amount</description>
        <inlineHelpText>This is the sum of Interest, Principal and Fees</inlineHelpText>
        <label>Transaction Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Transaction_Date__c</fullName>
        <defaultValue>$User.loan__Current_Branch_s_System_Date__c</defaultValue>
        <description>Transaction Date</description>
        <inlineHelpText>Transaction Date</inlineHelpText>
        <label>Transaction Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Loan Payment Transaction</label>
    <nameField>
        <displayFormat>LPT-{000000000}</displayFormat>
        <label>Loan Payment Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Payment Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/loan__Payment_Mode__c.object
<CustomObject>
    <label>Payment Mode</label>
    <nameField>
        <label>Payment Mode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Mode</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Virtual_Card__c.object
<CustomObject>
    <fields>
        <fullName>Card_Reference__c</fullName>
        <label>Card Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_Account__c</fullName>
        <label>CL Contract</label>
        <referenceTo>loan__Loan_Account__c</referenceTo>
        <relationshipLabel>Virtual Cards</relationshipLabel>
        <relationshipName>Virtual_Cards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Virtual Card</label>
    <nameField>
        <label>Virtual Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Virtual Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Virtual_Card_Payment__c.object
<CustomObject>
    <fields>
        <fullName>Loan_Payment_Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan Payment Transaction</label>
        <referenceTo>loan__Loan_Payment_Transaction__c</referenceTo>
        <relationshipLabel>Virtual Card Payments</relationshipLabel>
        <relationshipName>Virtual_Card_Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Amount__c</fullName>
        <label>Transaction Amount</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>REFUND</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Virtual_Card__c</fullName>
        <label>Virtual Card</label>
        <referenceTo>Virtual_Card__c</referenceTo>
        <relationshipLabel>Virtual Card Payments</relationshipLabel>
        <relationshipName>Virtual_Card_Payments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Virtual Card Payment</label>
    <nameField>
        <displayFormat>VCP-{000000000}</displayFormat>
        <label>Virtual Card Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Virtual Card Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RefundStatementHandler.cls
public class RefundStatementHandler {
    private List<RefundFileWrapper> txnsToProcess;
    private Map<String,Id> cardtoloanMap;
    private Map<Id,List<Virtual_Card_Payment__c>> loanToRefundTxnsMap;
    private List<Virtual_Card_Payment__c> refundTxnsToCreate;
    private Map<String,RefundFileWrapper> cardReftoWrapperObjMap;
    
    private loan__Payment_Mode__c pMode;
    private Date sysDate;
    private loan.GlobalLoanUtilFacade facade;
    
    private List<loan__Loan_Payment_Transaction__c> loanPaymentsToCreate;
    
    public RefundStatementHandler(List<RefundFileWrapper> txnsToProcess) {
        this.txnsToProcess = txnsToProcess;
        
        cardtoloanMap = new Map<String,Id>();
        loanToRefundTxnsMap = new Map<Id,List<Virtual_Card_Payment__c>>();
        refundTxnsToCreate = new List<Virtual_Card_Payment__c>();
        cardReftoWrapperObjMap = new Map<String,RefundFileWrapper>();
        
        loanPaymentsToCreate = new List<loan__Loan_Payment_Transaction__c>();
        
        pMode = [Select Id,Name from loan__Payment_Mode__C Where Name = 'Refund'];
        
        facade = new loan.GlobalLoanUtilFacade();
        sysDate = facade.getCurrentSystemDate();
        
    }
    
    public void handleStatement() {
    
        Set<String> cardReferences = new Set<String>();
        
        for(RefundFileWrapper rec : txnsToProcess) { 
            cardReftoWrapperObjMap.put(rec.strDestinationDetails,rec);
        }
        
        cardReferences = cardReftoWrapperObjMap.keyset();
        
        List<Virtual_Card__c> virtualCards = [Select Id,Name,
                                                     Loan_Account__c,
                                                     Card_Reference__c
                                              From Virtual_Card__c
                                              Where Card_Reference__c in: cardReferences
                                              and Card_Reference__c != null];
        
        System.debug(LoggingLevel.ERROR,' Virtual CArds found '+virtualCards.size());
        
        //Prepare map to get Loan ID for particular Card Reference.                                     
        if(!virtualCards.isEmpty()) {
            for(Virtual_CArd__c vCard : virtualCards) {
                cardtoloanMap.put(vCard.Card_Reference__c,vCard.Loan_account__c);
            }
            
            //Create Refund Transactions
            List<Virtual_Card_Payment__c> paymentList;
            Virtual_Card_Payment__c tempTxn;
            
            for(Virtual_CArd__c vCard : virtualCards) {
                
                //check if there are any txns for given loan.
                paymentList = loanToRefundTxnsMap.get(vCard.Loan_Account__c);
                
                if(paymentList == null ) {
                    //There is no payment already created for this loan
                    paymentList = new List<Virtual_Card_Payment__c>();
                    
                    //Create new virtual card refund txn.
                    tempTxn = getRefundPayment(vCard,cardReftoWrapperObjMap.get(vCard.Card_Reference__c));
                    
                    //Add to list
                    paymentList.add(tempTxn);
                    
                    //Add list to map for future iterations on list 45.
                    loanToRefundTxnsMap.put(vCard.Loan_Account__c,paymentList);
                    
                }else if(!paymentList.isEmpty()){
                    //There is/are payemnts on loan for other card references. Merge all later.
                    //Create new virtual card refund txn.
                    tempTxn = getRefundPayment(vCard,cardReftoWrapperObjMap.get(vCard.Card_Reference__c));
                    
                    //Add to list
                    paymentList.add(tempTxn);
                    
                    //Add list to map for future iterations on list 45.
                    loanToRefundTxnsMap.put(vCard.Loan_Account__c,paymentList);
                }
                
            }
            
            //Get consolidate Loan Payment for all virtual payments on same loan.
            for(Id loanId : loanToRefundTxnsMap.keyset()) {
                System.debug(LoggingLevel.ERROR,' In consolidate Payment for loop ');
                paymentList = loanToRefundTxnsMap.get(loanId);
                System.debug(LoggingLevel.ERROR,' Payment List for '+loanId+' '+paymentList.size());
                
                if(paymentList != null) {
                   refundTxnsToCreate.addAll(paymentList);
                   loanPaymentsToCreate.add(getConsolidatedLoanPayment(loanId,sysDate,paymentList));
                }else {
                    //no payments to create for given loan.
                }
            }
            
            //Insert loan payments.
            Savepoint sp = Database.setSavePoint();
            try {
                insert loanPaymentsToCreate;
                
                for(loan__Loan_Payment_Transaction__C lpt : loanPaymentsToCreate) {
                    lpt.loan__Cleared__c = true;
                }
                
                update loanPaymentsToCreate;
                
                insert refundTxnsToCreate;
            }catch(Exception e){
                Database.rollback(sp);
                throw e;
            }
            
            //Update Loan Payment Reference on Virtual Payments.
            refundTxnsToCreate = new List<Virtual_Card_Payment__c>();
            for(loan__Loan_Payment_Transaction__c lpt : loanPaymentsToCreate) {
                paymentList = loanToRefundTxnsMap.get(lpt.loan__Loan_Account__c);
                
                if(paymentList != null) {
                    
                    for(Virtual_Card_Payment__c vPayment : paymentList) {
                        vPayment.Loan_Payment_Transaction__c = lpt.Id;
                    }
                    refundTxnsToCreate.addAll(paymentList);
                }
            }
            
            //update Virtual CArd payments with LPT reference.
            try {
                update refundTxnsToCreate;
            }catch(Exception e){
                Database.rollback(sp);
                throw e;
            }
            
        }else {
            //No virtual cards found in system. goes to exception report.
            throw new GeneralException('No Virtual Cards found for received references');
        }
        
    }
    
    private loan__Loan_Payment_Transaction__c getConsolidatedLoanPayment(Id loanId, Date txnDate,
                                                                         List<Virtual_Card_Payment__c> pList) {
        loan__Loan_Payment_Transaction__c retVal;
        
        //calculate total amount
        Decimal txnAmount = 0;
        for(Virtual_Card_Payment__c vPayment : pList){
            txnAmount += vPayment.Transaction_Amount__c;
        }
        
        //Create Loan Payment.
        retVal = new loan__Loan_Payment_Transaction__c();
        retVal.loan__Loan_Account__c = loanId;
        retVal.loan__transaction_amount__c = txnAmount;
        retVal.loan__Payment_Mode__c = pMode.Id;
        retVal.loan__Transaction_date__c = txnDate;
        retVal.loan__Payment_Application_Mode__c = 'Current Dues';
        
        return retVal;
    }
    
    private Virtual_Card_Payment__c getRefundPayment(Virtual_CArd__c vCard, RefundFileWrapper txnRec) {
        Virtual_Card_Payment__c retVal = new Virtual_Card_Payment__c();
        
        retVal.Transaction_Amount__c = Decimal.valueOf(txnRec.strTransactionAmount);
        
        Datetime dt = Datetime.parse(txnRec.strTrasactionDate);
        retVal.Transaction_Date__c = dt.date();
        
        retVal.Virtual_Card__c = vCard.Id;
        retVal.Transaction_Type__c = 'REFUND';
        
        return retVal;
    }
}