src/objects/loan__Loan_Account__c.object
<CustomObject>
    <description>Lending Account</description>
    <fields>
        <fullName>loan__Credit_Limit__c</fullName>
        <description>Credit Limit for Line of Credit</description>
        <inlineHelpText>This is the contractual maximum advance limit, total advance withdrawn must not exceed this limit.</inlineHelpText>
        <label>Credit Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Minimum_Draw_Amount__c</fullName>
        <defaultValue>0.00</defaultValue>
        <inlineHelpText>Minimum advance amount which can be drawn by customer, applicable for line of credits.</inlineHelpText>
        <label>Minimum Draw Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Minimum_Due_Amount_On_Billing__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Minimum Bill Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_account_Due_Details__c.object
<CustomObject>
    <description>Invoices/bills for customer loans.</description>
    <fields>
        <fullName>loan__Due_Amt__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Due Amount</description>
        <label>Due Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Loan_Account__c</fullName>
        <label>Loan Account</label>
        <referenceTo>loan__Loan_Account__c</referenceTo>
        <relationshipName>Dues_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Bills</label>
    <nameField>
        <displayFormat>PCN-{0000000000}</displayFormat>
        <label>Due Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BillsTriggerCustomhandler.cls
public with sharing class BillsTriggerCustomhandler {
    
    private List<loan__Loan_account_Due_Details__c> newList;
    private Map<Id,loan__Loan_account_Due_Details__c> oldMap;
    
    private Id rtId;
    private Map<Id,loan__Loan_Account__c> loanMap;
    
    private Set<Id> loanIds;
    
    public BillsTriggerCustomhandler(List<loan__Loan_account_Due_Details__c> newList, Map<Id,loan__Loan_account_Due_Details__c> oldMap) {
    
        this.newList = newList;
        this.oldMap = oldMap;
        loanIds = new Set<ID>();
        
        for(loan__Loan_account_Due_Details__c d : newList){
            loanIds.add(d.loan__Loan_Account__c);
        }
        
        loanMap = new Map<Id,loan__Loan_Account__c>([Select Id,Name,
                                                            RecordTypeId,
                                                            loan__Credit_Limit__c,
                                                            loan__Minimum_Draw_Amount__c,
                                                            loan__Minimum_Due_Amount_On_Billing__c
                                                     From loan__Loan_Account__c
                                                     Where Id in: loanIds]);
        
        rtId = [Select Id,Name 
                From RecordType Where DeveloperName = 'Line_Of_Credit_Record_Type' 
                AND sObjectType = 'loan__Loan_Account__c'].Id;
    
    }
    
    public void onAfterInsert(){ 
        loan__Loan_Account__c loan;
        
        for(loan__Loan_account_Due_Details__c lDetails : newList) {
            loan = loanMap.get(lDetails.loan__Loan_Account__c);
            if(loan.RecordTypeId == rtId
                && loan.loan__Minimum_Due_Amount_On_Billing__c != null
                && loan.loan__Minimum_Due_Amount_On_Billing__c > 0
                && loan.loan__Minimum_Due_Amount_On_Billing__c < 25){
                
                lDetails.loan__Due_Amt__c = loan.loan__Minimum_Due_Amount_On_Billing__c;
            }
        }
        
    }
}