src/objects/loan__Currency__c.object
<CustomObject>
    <description>Currency</description>
    <label>Currency</label>
    <nameField>
        <label>Currency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Fee__c.object
<CustomObject>
    <description>Fee</description>
    <fields>
        <fullName>loan__Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Currency</description>
        <inlineHelpText>Currency</inlineHelpText>
        <label>Currency</label>
        <referenceTo>loan__Currency__c</referenceTo>
        <relationshipLabel>Fees</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Time_of_charge__c</fullName>
        <description>Time of charge</description>
        <inlineHelpText>Time of charge</inlineHelpText>
        <label>Time of charge</label>
        <picklist>
            <controllingField>loan__Fee_Category__c</controllingField>
            <picklistValues>
                <fullName>Late Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pay-Off Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSF Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wire Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Periodic Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Amortized Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Time of Disbursement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Paid Fees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Esker</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Fee</label>
    <nameField>
        <label>Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Fee_Junction__c.object
<CustomObject>
    <fields>
        <fullName>loan__Fee_Set__c</fullName>
        <label>Fee Set</label>
        <referenceTo>loan__Fee_Set__c</referenceTo>
        <relationshipName>Fee_Junction</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>loan__Fee__c</fullName>
        <label>Fee</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>loan__Fee__c.loan__Time_of_charge__c</field>
                <operation>notEqual</operation>
                <value>Pre-Paid Fees</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>loan__Fee__c</referenceTo>
        <relationshipLabel>Fee Set/Fee</relationshipLabel>
        <relationshipName>Fee_Junction</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Fee Set/Fee</label>
    <nameField>
        <displayFormat>FJIP-{0000000000}</displayFormat>
        <label>Fee Junction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fee Set/Fee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/loan__Fee_Set__c.object
<CustomObject>
    <description>A set of fee</description>
    <label>Fee Set</label>
    <nameField>
        <label>Fee Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fee Set</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_Account__c.object
<CustomObject>
    <description>Lending Account</description>
    <fields>
        <fullName>loan__Fee_Set__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Fee Set</description>
        <inlineHelpText>Lookup to associate the fee set on this lending account. Only the fees defined within the fee set can be assessed on this contract.
To create a fee set, Servicing configuration-&gt;Product-&gt;Manage fee set</inlineHelpText>
        <label>Fee Set</label>
        <referenceTo>loan__Fee_Set__c</referenceTo>
        <relationshipName>Loan_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Loan_Purpose__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Loan Purpose</description>
        <inlineHelpText>Loan purpose</inlineHelpText>
        <label>Purpose</label>
        <referenceTo>loan__Loan_Purpose__c</referenceTo>
        <relationshipName>Loan_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Payment_Application_Mode__c</fullName>
        <description>If the value is Future Dues, Reserve Amount For Next Due will be used for satisfying Bills. Otherwise, Reserve Amount For Next Due will not be used for satisfying Bills.</description>
        <inlineHelpText>Possible values are 
1) Future Dues
2) Current Dues
Future Dues is used when Loan Payments should be used to satisfy future dues.
Current Dues is used when Loan Payments should only be used to satisfy present dues.</inlineHelpText>
        <label>Payment Application Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Future Dues</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Current Dues</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_Product__c.object
<CustomObject>
    <description>Lending Product Definition1</description>
    <fields>
        <fullName>loan__Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Currency</description>
        <inlineHelpText>Currency</inlineHelpText>
        <label>Currency</label>
        <referenceTo>loan__Currency__c</referenceTo>
        <relationshipName>Loan_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Fee_Set__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fee Set</description>
        <inlineHelpText>Fee set contains the details of all the fees associated with the loan.</inlineHelpText>
        <label>Fee Set</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected Fee Set&apos;s category must be of type &apos;Loan&apos; and it should include at least one fee.</errorMessage>
            <filterItems>
                <field>loan__Fee_Set__c.loan__Fee_Set_Category__c</field>
                <operation>equals</operation>
                <value>Loan</value>
            </filterItems>
            <filterItems>
                <field>loan__Fee_Set__c.loan__Number_of_Fees__c</field>
                <operation>notEqual</operation>
                <value>0</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>loan__Fee_Set__c</referenceTo>
        <relationshipName>Loan_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Payment_Application_Mode__c</fullName>
        <description>If the value is Future Dues, Reserve Amount For Next Due will be used for satisfying Bills. Otherwise, Reserve Amount For Next Due will not be used for satisfying Bills.</description>
        <inlineHelpText>Select Future Dues if the loan payments must be used to satisfy future dues. 
 Select Current Dues if the loan payments must be used to to satisfy present dues.</inlineHelpText>
        <label>Payment Application Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Future Dues</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Current Dues</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Lending Product</label>
    <nameField>
        <label>Loan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lending Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_Purpose__c.object
<CustomObject>
    <description>Loan Purpose</description>
    <label>Loan Purpose</label>
    <nameField>
        <label>Loan Purpose Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Purpose</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__MF_Account__c.object
<CustomObject>
    <label>GL Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Office_Name__c.object
<CustomObject>
    <description>Name of the office</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestWSFNPLCases.cls
@isTest
public class TestWSFNPLCases {
    private static Contact c;
    private static loan__Loan_Account__c loanAccount;
    
    @testSetup static void createSeedData() {
        System.debug(LoggingLevel.eRROR,' running test data ');
        loan.TestHelper.createSeedDataForTesting();
        
        loan__Currency__c curr = loan.TestHelper.createCurrency();
        //Create a dummy MF_Account
        loan__MF_Account__c dummyAccount = loan.TestHelper.createMFAccount('XXXAccountForTest','10000 - ASSETS');
        loan__MF_Account__c dummyIncAccount = loan.TestHelper.createMFAccount('XXXIncAccountForTest','30000 - INCOME');
        
        //Create a Fee Set
        loan__Fee__c dummyFee = loan.TestHelper.createFee(curr,dummyIncAccount ,dummyAccount); 
        dummyFee.loan__Time_OF_Charge__c = 'Esker';
        update dummyFee;
                                           
        loan__Fee_Set__c dummyFeeSet = loan.TestHelper.createFeeSet();
        loan__Fee_Junction__c dummyFeeJunction = loan.TestHelper.createFeeJunction(dummyFee,dummyFeeSet);
        
        loan__Office_Name__c dummyOffice = loan.TestHelper.createOffice();
        
        //Create a dummy Loan Product
        loan__Loan_Product__c dummyLP = loan.TestHelper.createLoanProduct(dummyOffice,
                            dummyAccount, 
                            curr, 
                            dummyFeeSet);
        dummyLP.loan__Payment_Application_Mode__c = loan.LoanConstants.LOAN_PAYMENT_APPLICATION_CURRENT_DUES;
        
        update dummyLP;
        
        //System.debug(LoggingLevel.ERROR,'LoanProduct in test: ' + dummyLP.Disable_Reserve_Amount_for_Next_Due__c);
        loan__Loan_Purpose__c dummyLoanPurpose = loan.TestHelper.createLoanPurpose();        
        
        c = new Contact(LastName = 'Test');
        c.Email = 'utkarsh@cloudlendinginc.com';
        c.MailingCity = 'RYE';
        c.MailingStreet = '22 Tower Street';
        c.MailingState = 'East Sussex';
        c.MailingCountry = 'GB';
        c.MailingPostalCode = 'TN31 7AT';
        insert c;
        
        //Create a dummy Loan Account
        loanAccount = loan.TestHelper.createLoanAccountForContactObj(dummyLP,
                                                    c,
                                                    dummyFeeSet,
                                                    dummyLoanPurpose,
                                                    dummyOffice);
        
    }
    
    static testMethod void testGetcase() {
    
        loanAccount = [Select Id,Name from loan__Loan_Account__C limit 1];

        RestRequest req         = new RestRequest(); 
        RestResponse res        = new RestResponse();
        req.requestURI          = '/services/apexrest/v1/cases';  
        req.addParameter('Cid', '00325000003i29qs');
        req.httpMethod          = 'GET';
        RestContext.request     = req;
        RestContext.response    = res;
        case caseobj= new case();
        case[] caseobjq         = null;
            contact conobj      = new contact();
            conobj.LastName     ='Test';
            conobj.Email        ='Test@Flynowpaylater.com';
            insert conobj;
            caseobj.Subject     ='Test Subject';
            caseobj.Description ='Test Description';
            caseobj.ContactId   ='00325000003i29q';//conobj.Id;
            insert  caseobj;
            system.debug('caseobj'+caseobj);
                caseobjq=[select Subject,Description,status from case where contact.id=:caseobj.ContactId ];
                string casenum      ='100';
                ResponseCase results=new ResponseCase ();
                results.openCase('message', 'status', 'Errmessage', 'Errcode', caseobjq);
                results.noOpenCase('message',' status',' Errmessage',' Errcode');
                results.noValidEmail('message', 'status', 'Errmessage', 'Errcode');
                results.postCaseError('message', 'status', 'Errmessage', 'Errcode');
                results.postCaseBlankInputError('message', 'status', 'Errmessage', 'Errcode');
                results.postCaseSuccess('message', 'status', 'Errmessage', 'Errcode', casenum);
                ResponseCase r = WSFNPLCases.getCases();
          
                //HTTP POST Method Invoke        
                RestRequest req1            = new RestRequest(); 
                RestResponse res1           = new RestResponse();
                req.requestURI              = '/services/apexrest/v1/cases';  
                req.httpMethod              = 'POST';
                RestContext.request         = req1;
                RestContext.response        = res1;

                Contact conoobj             = new contact(Lastname='test',email='k@gmail.com');
                list <contact> con          =new list<contact>();
                con.add(conoobj);
                insert conoobj;
                system.debug('conoobj'+conoobj);
                system.debug('ccon'+con);
                
                case casepost               =new case();
                casepost.Subject            = 'Subject' ;
                casepost.Description        = 'Description' ;
                casepost.ContactId          = conoobj.id;
                casepost.Origin             ='Web';
                casepost.Status             ='Open';
                insert casepost;
                System.assert(con.size()!=0);
         
                ResponseCase rr=WSFNPLCases.createCase('', '', conobj.id,'');
                ResponseCase rr1=WSFNPLCases.createCase('', 'Description',conobj.id,'');
                ResponseCase rr3=WSFNPLCases.createCase('Subject', '',conobj.id,'');
                ResponseCase rr4=WSFNPLCases.createCase('Subject', 'Description', conobj.id,'');
                ResponseCase rr5=WSFNPLCases.createCase('Subject', 'Description', conobj.id,loanAccount.Id);
              
    }

}