src/objects/loan__Batch_Process_Log__c.object
<CustomObject>
    <fields>
        <fullName>loan__Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>loan__Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Batch Process Log</label>
    <nameField>
        <label>Apex Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Process Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_Account__c.object
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BrokerReverseCommissionDisbJob.cls
public class BrokerReverseCommissionDisbJob implements Database.Batchable<sObject>, Schedulable {
    private String query;
    private List<loan__Batch_Process_Log__c> blogs;
    private loan.GlobalLoanUtilFacade facade;
    private Date sysDate;
    private List<loan__Loan_Account__c> loans;
    
    /* Constructor */
    public BrokerReverseCommissionDisbJob() {
        facade = new loan.GlobalLoanUtilFacade();
        sysDate = facade.getCurrentSystemDate();
        this.query = ProcessJobQueryUtil.getBrokerCommissionJobQuery(sysDate);
        
        bLogs = new List<loan__Batch_Process_Log__c>();
        
    }
    
    public void execute(SchedulableContext sc) {
        
    }
        
    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bc, List<sObject> scope) {
        loans = (List<loan__Loan_Account__c>) scope;
        
        try{
            BrokerReverseCommissiondisbJobHandler handler = new BrokerReverseCommissiondisbJobHandler(loans);
            handler.process();
        }catch(Exception e) {
            loan__Batch_Process_Log__c errorLog = new loan__Batch_Process_Log__c();
            errorLog.loan__Message__c = 'Error : LoanPaymentTransactionAchJob: '+e.getMessage()+' from line '+e.getLineNumber();
            errorLog.loan__Date__c = Date.newInstance(System.now().year(),System.now().month(),System.now().day());
            
            bLogs.add(errorLog);
            insert bLogs;
        }
    }
    
    public void finish(Database.BatchableContext bc){
    
    }
}