src/objects/loan__Loan_Account__c.object
<CustomObject>
    <description>Lending Account</description>
    <fields>
        <fullName>Is_Expired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>loan__Invalid_Data__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If system identify any data issues with this lending account, the reasons will be displayed on the top of lending account and this flag will be checked.
Once the issues are fixed, this flag will be unchecked by system.
User should not modify this flag.</inlineHelpText>
        <label>Invalid Data</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>loan__Loan_Status__c</fullName>
        <inlineHelpText>Status of the Account, expected values are :
Pending Approval
Active - Good Standing
Active - Bad Standing
Active - Matured
Approved
Canceled
Closed - Obligations met
Closed- Written Off
Closed - Refinanced
Partial Application</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Partial Application</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active - Good Standing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active - Bad Standing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Obligations met</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed- Written Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Refinanced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active - Matured</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_Status__c.object
<CustomObject>
    <description>Object for storing Loan Statuses</description>
    <label>Loan Status</label>
    <nameField>
        <label>Loan Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LineOfCreditExpiryJob.cls
global class LineOfCreditExpiryJob implements Database.Batchable<sObject>, Schedulable {
    
    private static String NAME = 'LOC EXPIRY';
    private Date iDate;
    private Boolean submitNextJob = true;
    private loan.GlobalLoanUtilFacade facade;
    private String query;
    
    global LineOfCreditExpiryJob() {
        facade = new loan.GlobalLoanUtilFacade();
        iDate = facade.getCurrentSystemDate();
        
        query = ProcessJobQueryUtil.getLocExpiryQuery(iDate);
        System.debug(LoggingLevel.ERROR,' Query '+query);
    }
    
    global void execute(SchedulableContext sc) {
        LineOfCreditExpiryJob j = new LineOfCreditExpiryJob();
        Database.executeBatch(j);

    }
    
    global Database.querylocator Start(Database.BatchableContext bc){
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<SObject> scope){
        List<loan__Loan_Account__c> locs = (List<loan__Loan_Account__c>)scope;
        
        //Expire Locs
        for(loan__Loan_Account__c loc : locs) {
            loc.Is_Expired__c = true;
            loc.loan__Invalid_Data__c = true;
            
            loc.loan__Loan_Status__c = 'Expired';
        }
        
        update locs;
    }
    
    global void finish(Database.BatchableContext bc){
    
    }
}