src/objects/loan__Loan_Account__c.object
<CustomObject>
    <description>Lending Account</description>
    <fields>
        <fullName>Total_payments__c</fullName>
        <label>Total payments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Repayment_Schedule__c.object
<CustomObject>
    <description>Amortization schedule is also called as Repayment schedule.</description>
    <fields>
        <fullName>loan__Loan_Account__c</fullName>
        <description>Repayment Schedule of which Loan account</description>
        <inlineHelpText>Repayment Schedule of which Loan account</inlineHelpText>
        <label>Loan Account</label>
        <referenceTo>loan__Loan_Account__c</referenceTo>
        <relationshipName>Repayment_Schedule</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>loan__Paid_Total__c</fullName>
        <formula>loan__Total_Paid_Fees__c +  loan__Paid_Interest__c +  loan__Paid_Principal__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Paid Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Amortization Schedule</label>
    <nameField>
        <displayFormat>RSI-{0000000000}</displayFormat>
        <label>Repayment Schedule ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amortization Schedule</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TotalAMountEventHandler.cls
public class TotalAMountEventHandler
{
    public static void SomeMethod(List<loan__Repayment_Schedule__c> newOpp,List<loan__Repayment_Schedule__c> oldOpp,Boolean IsInsert,Boolean IsUpdate,Boolean IsDelete)
    {
        set<id> oppAccId=new set<id>();
        if(IsInsert)
        {
            for(loan__Repayment_Schedule__c op:newOpp)
            {
                oppAccId.add(op.Id);
            }
        }
        if(IsUpdate||IsDelete)
        {
            for(loan__Repayment_Schedule__c o:oldOpp)
            {
                oppAccId.add(o.loan__Loan_Account__c);
            }
        }
        Map<Id,loan__Loan_Account__c> amap=new Map<Id,loan__Loan_Account__c>([select id,name from loan__Loan_Account__c where id in:oppAccId]);
        List<loan__Loan_Account__c> toUpdate=new List<loan__Loan_Account__c>();
        for(loan__Loan_Account__c a:[select id,name,(select id,loan__Loan_Account__c,loan__Paid_Total__c from loan__Repayment_Schedule__r),Total_payments__c from loan__Loan_Account__c where id in:oppAccId])
        {
            decimal count=0;
            if(amap.containsKey(a.id))
            {
                
                for(integer i=0;i<a.loan__Repayment_Schedule__r.size();i++)
                {
                    count=count+a.loan__Repayment_Schedule__r[i].loan__Paid_Total__c ;
                }
            }
            amap.get(a.id).Total_payments__c=count;
            toUpdate.add(amap.get(a.id));
            
        }
        update toUpdate;
    }
  /*public  void BeforeUpdate(List<loan__Repayment_Schedule__c> newOpp)
   {
       for(loan__Repayment_Schedule__co:newOpp)
       {
           if(o.Description==null)
           {
               o.Description='From Trigger In Event Handler';
           }
       }
   }*/

}