src/objects/loan__Currency__c.object
<CustomObject>
    <description>Currency</description>
    <label>Currency</label>
    <nameField>
        <label>Currency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Currencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Fee__c.object
<CustomObject>
    <description>Fee</description>
    <fields>
        <fullName>loan__Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Currency</description>
        <inlineHelpText>Currency</inlineHelpText>
        <label>Currency</label>
        <referenceTo>loan__Currency__c</referenceTo>
        <relationshipLabel>Fees</relationshipLabel>
        <relationshipName>Fees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fee</label>
    <nameField>
        <label>Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Fee_Junction__c.object
<CustomObject>
    <fields>
        <fullName>loan__Fee_Set__c</fullName>
        <label>Fee Set</label>
        <referenceTo>loan__Fee_Set__c</referenceTo>
        <relationshipName>Fee_Junction</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>loan__Fee__c</fullName>
        <label>Fee</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>loan__Fee__c.loan__Time_of_charge__c</field>
                <operation>notEqual</operation>
                <value>Pre-Paid Fees</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>loan__Fee__c</referenceTo>
        <relationshipLabel>Fee Set/Fee</relationshipLabel>
        <relationshipName>Fee_Junction</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Fee Set/Fee</label>
    <nameField>
        <displayFormat>FJIP-{0000000000}</displayFormat>
        <label>Fee Junction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fee Set/Fee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/loan__Fee_Set__c.object
<CustomObject>
    <description>A set of fee</description>
    <label>Fee Set</label>
    <nameField>
        <label>Fee Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fee Set</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_Product__c.object
<CustomObject>
    <description>Lending Product Definition1</description>
    <fields>
        <fullName>loan__Currency__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Currency</description>
        <inlineHelpText>Currency</inlineHelpText>
        <label>Currency</label>
        <referenceTo>loan__Currency__c</referenceTo>
        <relationshipName>Loan_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Fee_Set__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Fee Set</description>
        <inlineHelpText>Fee set contains the details of all the fees associated with the loan.</inlineHelpText>
        <label>Fee Set</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected Fee Set&apos;s category must be of type &apos;Loan&apos; and it should include at least one fee.</errorMessage>
            <filterItems>
                <field>loan__Fee_Set__c.loan__Fee_Set_Category__c</field>
                <operation>equals</operation>
                <value>Loan</value>
            </filterItems>
            <filterItems>
                <field>loan__Fee_Set__c.loan__Number_of_Fees__c</field>
                <operation>notEqual</operation>
                <value>0</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>loan__Fee_Set__c</referenceTo>
        <relationshipName>Loan_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Loan_Product_Type__c</fullName>
        <inlineHelpText>Type of Product, Possible values are 
a) Loan
b) Line of Credit
c) Amortization Based Loan
d) Merchant Cash Advance</inlineHelpText>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Loan</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Line of Credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Merchant Cash Advance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amz Based Loan</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>loan__Payment_Application_Mode__c</fullName>
        <description>If the value is Future Dues, Reserve Amount For Next Due will be used for satisfying Bills. Otherwise, Reserve Amount For Next Due will not be used for satisfying Bills.</description>
        <inlineHelpText>Select Future Dues if the loan payments must be used to satisfy future dues. 
 Select Current Dues if the loan payments must be used to to satisfy present dues.</inlineHelpText>
        <label>Payment Application Mode</label>
        <picklist>
            <picklistValues>
                <fullName>Future Dues</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Current Dues</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Lending Product</label>
    <nameField>
        <label>Loan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lending Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__MF_Account__c.object
<CustomObject>
    <label>GL Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Office_Name__c.object
<CustomObject>
    <description>Name of the office</description>
    <label>Company</label>
    <nameField>
        <label>Company</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Test_WSLocAccounts_v1.cls
@isTest
public class Test_WSLocAccounts_v1 {
  
   public static Contact objCon(){
    Contact  objContact = new Contact();
    objContact.FirstName = 'testContact1';
    objContact.LastName  = 'TestContact2';
    return objContact;
   }
   
    @isTest static void test_method_WSLocAccounts_v1_0_0() {
        // Implement test code
        Map<String,Object> reqBodyMap = new Map<String,Object>();
        reqBodyMap.put('borrowerId1', '123456789012345');
        RestRequest req  = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/v1/lineofcredit';
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;
        Test.startTest();
         Response results = WSLocAccounts_v1.createLoanAccount();
        Test.stopTest();
    }

    @isTest static void test_method_WSLocAccounts_v1_0() {
        // Implement test code
       Contact objCon = Test_WSLocAccounts_v1.objCon();
       insert objCon ;
        Map<String,Object> reqBodyMap = new Map<String,Object>();
        reqBodyMap.put('borrowerId', objCon.id);
        RestRequest req  = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/v1/lineofcredit';
        req.requestBody = Blob.valueOf(JSON.serialize(reqBodyMap));
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
         Response results = WSLocAccounts_v1.createLoanAccount();
        Test.stopTest();
    }

   
  @isTest static void test_method_WSLocAccounts_v1_1() {
        // Implement test code
        Contact objCon = Test_WSLocAccounts_v1.objCon();
        insert objCon ;
        RestRequest req  = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/v1/lineofcredit';
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
        Response results = WSLocAccounts_v1.createLoanAccount();
        Test.stopTest();
    }

    
    @isTest static void test_method_WSLocAccounts_v1_2() {
        // Implement test code
        Contact objCon = Test_WSLocAccounts_v1.objCon();
        insert objCon ;
        Map<String,Object> reqBodyMap = new Map<String,Object>();
        reqBodyMap.put('borrowerId', null);
        reqBodyMap.put('loanProductId',objCon.id);
        reqBodyMap.put('loanAmount', 1200);
        reqBodyMap.put('term',3);
        reqBodyMap.put('interestRate',3);
        reqBodyMap.put('purpose','testing');
        reqBodyMap.put('expectedDisbursalDate',date.today());
        reqBodyMap.put('firstInstallmentDate',date.today());
        reqBodyMap.put('frequencyOfPayment', '2');
        reqBodyMap.put('interestOnlyPeriod', 3);
        reqBodyMap.put('balloonPayment', 123);
        RestRequest req  = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/v1/lineofcredit';
        req.requestBody = Blob.valueOf(JSON.serialize(reqBodyMap));
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
         Response results = WSLocAccounts_v1.createLoanAccount();
        Test.stopTest();
    }


    @isTest static void test_method_WSLocAccounts_v1_3() {
        // Implement test code
         Contact objCon = Test_WSLocAccounts_v1.objCon();
         insert objCon ;
        Map<String,Object> reqBodyMap = new Map<String,Object>();
        reqBodyMap.put('borrowerId',objCon.id);
        reqBodyMap.put('loanProductId',string.valueOf(objCon.id));
        reqBodyMap.put('loanAmount', null);
        reqBodyMap.put('term',3);
        reqBodyMap.put('interestRate',3);
        reqBodyMap.put('purpose','testing');
        reqBodyMap.put('expectedDisbursalDate',date.today());
        reqBodyMap.put('firstInstallmentDate',date.today());
        reqBodyMap.put('frequencyOfPayment', '2');
        reqBodyMap.put('interestOnlyPeriod', 3);
        reqBodyMap.put('balloonPayment', 123);
        RestRequest req  = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/v1/lineofcredit';
        req.requestBody = Blob.valueOf(JSON.serialize(reqBodyMap));
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
         Response results = WSLocAccounts_v1.createLoanAccount();
        Test.stopTest();
    }

    @isTest static void test_method_WSLocAccounts_v1_4() {
        // Implement test code
       Contact objCon = Test_WSLocAccounts_v1.objCon();
       insert objCon ;
        Map<String,Object> reqBodyMap = new Map<String,Object>();
        reqBodyMap.put('borrowerId',objCon.id);
        reqBodyMap.put('loanProductId',string.valueOf(objCon.id));
        reqBodyMap.put('loanAmount', 2000);
        reqBodyMap.put('term',null);
        reqBodyMap.put('interestRate',2);
        reqBodyMap.put('purpose','test');
        reqBodyMap.put('expectedDisbursalDate',date.today());
        reqBodyMap.put('firstInstallmentDate',date.today());
        reqBodyMap.put('frequencyOfPayment', '1');
        reqBodyMap.put('interestOnlyPeriod', 1);
        reqBodyMap.put('balloonPayment',2);
        RestRequest req  = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/v1/lineofcredit';
        req.requestBody = Blob.valueOf(JSON.serialize(reqBodyMap));
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;

        Test.startTest();
         Response results = WSLocAccounts_v1.createLoanAccount();
        Test.stopTest();
    }
    
     @isTest static void test_method_WSLocAccounts_v1_5() {
       Contact objCon = Test_WSLocAccounts_v1.objCon();
       insert objCon ;
       
        loan.TestHelper.createSeedDataForTesting();
        
        loan__Currency__c curr = loan.TestHelper.createCurrency();
        //Create a dummy MF_Account
        loan__MF_Account__c dummyAccount = loan.TestHelper.createMFAccount('XXXAccountForTest','10000 - ASSETS');
        loan__MF_Account__c dummyIncAccount = loan.TestHelper.createMFAccount('XXXIncAccountForTest','30000 - INCOME');
        
        //Create a Fee Set
        loan__Fee__c dummyFee = loan.TestHelper.createFee(curr,dummyIncAccount ,dummyAccount);                                    
        loan__Fee_Set__c dummyFeeSet = loan.TestHelper.createFeeSet();
        loan__Fee_Junction__c dummyFeeJunction = loan.TestHelper.createFeeJunction(dummyFee,dummyFeeSet);
        
        loan__Office_Name__c dummyOffice = loan.TestHelper.createOffice();
        
        //Create a dummy Loan Product
        loan__Loan_Product__c dummyLP = loan.TestHelper.createLocProduct('testData',
         dummyOffice, dummyAccount, curr, dummyFeeSet,'TestData',2, 2, 'Test');
         
        dummyLP.loan__Payment_Application_Mode__c = loan.LoanConstants.LOAN_PAYMENT_APPLICATION_CURRENT_DUES;
        dummyLP.loan__Loan_Product_Type__c = 'Line of Credit';
        update dummyLP;
       
        Map<String,Object> reqBodyMap = new Map<String,Object>();
        reqBodyMap.put('borrowerId',objCon.id);
        reqBodyMap.put('loanProductId',string.valueOf(objCon.id));
        reqBodyMap.put('loanAmount', 2000);
        reqBodyMap.put('term',2);
        reqBodyMap.put('interestRate',2);
        reqBodyMap.put('purpose','test');
        reqBodyMap.put('expectedDisbursalDate',date.today());
        reqBodyMap.put('firstInstallmentDate',date.today());
        reqBodyMap.put('frequencyOfPayment', '1');
        reqBodyMap.put('interestOnlyPeriod', 1);
        reqBodyMap.put('balloonPayment',2);
         RestRequest req  = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/v1/lineofcredit';
        req.requestBody = Blob.valueOf(JSON.serialize(reqBodyMap));
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;
        Test.startTest();
        Response results = WSLocAccounts_v1.createLoanAccount();
        Test.stopTest();
    }
    
     @isTest static void test_method_WSLocAccounts_v1_6() {
       Contact objCon = Test_WSLocAccounts_v1.objCon();
       insert objCon ;
       
        loan.TestHelper.createSeedDataForTesting();
        
        loan__Currency__c curr = loan.TestHelper.createCurrency();
        //Create a dummy MF_Account
        loan__MF_Account__c dummyAccount = loan.TestHelper.createMFAccount('XXXAccountForTest','10000 - ASSETS');
        loan__MF_Account__c dummyIncAccount = loan.TestHelper.createMFAccount('XXXIncAccountForTest','30000 - INCOME');
        
        //Create a Fee Set
        loan__Fee__c dummyFee = loan.TestHelper.createFee(curr,dummyIncAccount ,dummyAccount);                                    
        loan__Fee_Set__c dummyFeeSet = loan.TestHelper.createFeeSet();
        loan__Fee_Junction__c dummyFeeJunction = loan.TestHelper.createFeeJunction(dummyFee,dummyFeeSet);
        
        loan__Office_Name__c dummyOffice = loan.TestHelper.createOffice();
        
        //Create a dummy Loan Product
        loan__Loan_Product__c dummyLP = loan.TestHelper.createLocProduct('testData',
         dummyOffice, dummyAccount, curr, dummyFeeSet,'TestData',2, 2, 'Test');
         
        dummyLP.loan__Payment_Application_Mode__c = loan.LoanConstants.LOAN_PAYMENT_APPLICATION_CURRENT_DUES;
        dummyLP.loan__Loan_Product_Type__c = 'Line of Credit';
        update dummyLP;
       
        Map<String,Object> reqBodyMap = new Map<String,Object>();
        reqBodyMap.put('borrowerId',null);
        reqBodyMap.put('loanProductId',string.valueOf(objCon.id));
        reqBodyMap.put('loanAmount', 2000);
        reqBodyMap.put('term',2);
        reqBodyMap.put('interestRate',2);
        reqBodyMap.put('purpose','test');
        reqBodyMap.put('expectedDisbursalDate',date.today());
        reqBodyMap.put('firstInstallmentDate',date.today());
        reqBodyMap.put('frequencyOfPayment', '1');
        reqBodyMap.put('interestOnlyPeriod', 1);
        reqBodyMap.put('balloonPayment',2);
         RestRequest req  = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/v1/lineofcredit';
        req.requestBody = Blob.valueOf(JSON.serialize(reqBodyMap));
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;
        Test.startTest();
        Response results = WSLocAccounts_v1.createLoanAccount();
        Test.stopTest();
    }
    
    @isTest static void test_method_WSLocAccounts_v1_7() {
       Contact objCon = Test_WSLocAccounts_v1.objCon();
       insert objCon ;
       
        loan.TestHelper.createSeedDataForTesting();
        
        loan__Currency__c curr = loan.TestHelper.createCurrency();
        //Create a dummy MF_Account
        loan__MF_Account__c dummyAccount = loan.TestHelper.createMFAccount('XXXAccountForTest','10000 - ASSETS');
        loan__MF_Account__c dummyIncAccount = loan.TestHelper.createMFAccount('XXXIncAccountForTest','30000 - INCOME');
        
        //Create a Fee Set
        loan__Fee__c dummyFee = loan.TestHelper.createFee(curr,dummyIncAccount ,dummyAccount);                                    
        loan__Fee_Set__c dummyFeeSet = loan.TestHelper.createFeeSet();
        loan__Fee_Junction__c dummyFeeJunction = loan.TestHelper.createFeeJunction(dummyFee,dummyFeeSet);
        
        loan__Office_Name__c dummyOffice = loan.TestHelper.createOffice();
        
        //Create a dummy Loan Product
        loan__Loan_Product__c dummyLP = loan.TestHelper.createLocProduct('testData',
         dummyOffice, dummyAccount, curr, dummyFeeSet,'TestData',2, 2, 'Test');
         
        dummyLP.loan__Payment_Application_Mode__c = loan.LoanConstants.LOAN_PAYMENT_APPLICATION_CURRENT_DUES;
        dummyLP.loan__Loan_Product_Type__c = 'Line of Credit';
        update dummyLP;
       
        Map<String,Object> reqBodyMap = new Map<String,Object>();
        reqBodyMap.put('borrowerId',objCon.id);
        reqBodyMap.put('loanProductId',string.valueOf(objCon.id));
        reqBodyMap.put('loanAmount', 2000);
        reqBodyMap.put('term',2);
        reqBodyMap.put('interestRate',2);
        reqBodyMap.put('purpose','test');
        reqBodyMap.put('expectedDisbursalDate',date.today());
        reqBodyMap.put('firstInstallmentDate',date.today());
        reqBodyMap.put('frequencyOfPayment', '1');
        reqBodyMap.put('interestOnlyPeriod', 1);
        reqBodyMap.put('balloonPayment',2);
         RestRequest req  = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/v1/lineofcredit';
        req.requestBody = Blob.valueOf(JSON.serialize(reqBodyMap));
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;
        Test.startTest();
        Response results = WSLocAccounts_v1.createLoanAccount();
        Test.stopTest();
    }
    
}