src/objects/loan__Batch_Process_Log__c.object
<CustomObject>
    <fields>
        <fullName>loan__Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>loan__Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Batch Process Log</label>
    <nameField>
        <label>Apex Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Process Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_Account__c.object
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_account_Due_Details__c.object
<CustomObject>
    <description>Invoices/bills for customer loans.</description>
    <fields>
        <fullName>Payment_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Payment Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>loan__Due_Amt__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Due Amount</description>
        <label>Due Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Due_Date__c</fullName>
        <description>Due date of the due.</description>
        <inlineHelpText>Due Date of the Due</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>loan__Loan_Account__c</fullName>
        <label>Loan Account</label>
        <referenceTo>loan__Loan_Account__c</referenceTo>
        <relationshipName>Dues_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>loan__Transaction_Date__c</fullName>
        <description>Transaction date</description>
        <inlineHelpText>Date on which the transaction got created.</inlineHelpText>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <label>Bills</label>
    <nameField>
        <displayFormat>PCN-{0000000000}</displayFormat>
        <label>Due Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/loan__Loan_Payment_Transaction__c.object
<CustomObject>
    <description>Loan Payment Transaction</description>
    <fields>
        <fullName>loan__Loan_Account__c</fullName>
        <description>Loan Account</description>
        <inlineHelpText>Loan Account</inlineHelpText>
        <label>Loan Account</label>
        <referenceTo>loan__Loan_Account__c</referenceTo>
        <relationshipLabel>Loan Payment Transactions</relationshipLabel>
        <relationshipName>Loan_Payment_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>loan__Payment_Mode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Mode</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>loan__Payment_Mode__c.Name</field>
                <operation>notEqual</operation>
                <value>Internal Transfer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>loan__Payment_Mode__c</referenceTo>
        <relationshipLabel>Loan Payment Transactions</relationshipLabel>
        <relationshipName>Loan_Payment_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Skip_Validation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Skip Validation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>loan__Transaction_Amount__c</fullName>
        <description>Transaction Amount</description>
        <inlineHelpText>This is the sum of Interest, Principal and Fees</inlineHelpText>
        <label>Transaction Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Transaction_Date__c</fullName>
        <defaultValue>$User.loan__Current_Branch_s_System_Date__c</defaultValue>
        <description>Transaction Date</description>
        <inlineHelpText>Transaction Date</inlineHelpText>
        <label>Transaction Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Loan Payment Transaction</label>
    <nameField>
        <displayFormat>LPT-{000000000}</displayFormat>
        <label>Loan Payment Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Payment Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/loan__Payment_Mode__c.object
<CustomObject>
    <label>Payment Mode</label>
    <nameField>
        <label>Payment Mode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Mode</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LoanPaymentTransactionAchJob.cls
public class LoanPaymentTransactionAchJob implements Database.Batchable<sObject>, Schedulable {
    private String query;
    private List<loan__Loan_Account_Due_Details__c> bills;
    private List<loan__Loan_Payment_Transaction__c> loanPayments;
    private loan__Payment_Mode__c pMode;
    private List<loan__Batch_Process_Log__c> blogs;
    
    /* Constructor */
    public LoanPaymentTransactionAchJob() {
        this.query = ProcessJobQueryUtil.getCustomACHLoc();
        
        loanPayments = new List<loan__Loan_Payment_Transaction__c>();
        bLogs = new List<loan__Batch_Process_Log__c>();
        
        pMode = [Select Id,Name from loan__Payment_Mode__c Where Name = 'ACH' limit 1];
    
    }
    
    public void execute(SchedulableContext sc) {
        
    }
        
    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bc, List<sObject> scope) {
       
        bills = (List<loan__Loan_Account_Due_Details__c>) scope;
        loan__Loan_Payment_Transaction__c lpt;
        loan__Batch_Process_Log__c errorLog;
        
        try{
            for(loan__Loan_Account_Due_Details__c due : bills){
                lpt = new loan__Loan_Payment_Transaction__c();
                lpt.loan__Transaction_Date__c = due.loan__Due_Date__c;
                lpt.loan__Transaction_Amount__c = due.loan__Due_Amt__c;
                lpt.loan__Payment_Mode__c = pMode.Id;
                lpt.loan__Loan_Account__c = due.loan__Loan_Account__c;
                lpt.loan__Skip_Validation__c = true;
                
                System.debug(LoggingLevel.ERROR,' Transaction Date '+lpt.loan__Transaction_Date__c);
                
                loanPayments.add(lpt);
            }
            
            insert loanPayments;
            
            for(loan__Loan_Account_Due_Details__c due : bills) {
                due.Payment_Created__c = true;
            }
            
            update bills;
        }catch(Exception e) {
            errorLog = new loan__Batch_Process_Log__c();
            errorLog.loan__Message__c = 'Error : LoanPaymentTransactionAchJob: '+e.getMessage()+' from line '+e.getLineNumber();
            errorLog.loan__Date__c = Date.newInstance(System.now().year(),System.now().month(),System.now().day());
            
            bLogs.add(errorLog);
            insert bLogs;
        }
    }
    
    public void finish(Database.BatchableContext bc){
    
    }
}