src/objects/loan__Batch_Process_Log__c.object
<CustomObject>
    <fields>
        <fullName>loan__Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>loan__Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Batch Process Log</label>
    <nameField>
        <label>Apex Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Process Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_Account__c.object
<CustomObject>
    <description>Lending Account</description>
    <label>CL Contract</label>
    <nameField>
        <displayFormat>LAI-{00000000}</displayFormat>
        <label>CL Contract ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CL Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/loan__Loan_Payment_Transaction__c.object
<CustomObject>
    <description>Loan Payment Transaction</description>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Regular</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Retry</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>loan__Loan_Account__c</fullName>
        <description>Loan Account</description>
        <inlineHelpText>Loan Account</inlineHelpText>
        <label>Loan Account</label>
        <referenceTo>loan__Loan_Account__c</referenceTo>
        <relationshipLabel>Loan Payment Transactions</relationshipLabel>
        <relationshipName>Loan_Payment_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>loan__Payment_Mode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Mode</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>loan__Payment_Mode__c.Name</field>
                <operation>notEqual</operation>
                <value>Internal Transfer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>loan__Payment_Mode__c</referenceTo>
        <relationshipLabel>Loan Payment Transactions</relationshipLabel>
        <relationshipName>Loan_Payment_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>loan__Receipt_Date__c</fullName>
        <defaultValue>$User.loan__Current_Branch_s_System_Date__c</defaultValue>
        <description>Receipt Date</description>
        <inlineHelpText>Receipt Date</inlineHelpText>
        <label>Receipt Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>loan__Transaction_Amount__c</fullName>
        <description>Transaction Amount</description>
        <inlineHelpText>This is the sum of Interest, Principal and Fees</inlineHelpText>
        <label>Transaction Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>loan__Transaction_Date__c</fullName>
        <defaultValue>$User.loan__Current_Branch_s_System_Date__c</defaultValue>
        <description>Transaction Date</description>
        <inlineHelpText>Transaction Date</inlineHelpText>
        <label>Transaction Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Loan Payment Transaction</label>
    <nameField>
        <displayFormat>LPT-{000000000}</displayFormat>
        <label>Loan Payment Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Payment Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/loan__Payment_Mode__c.object
<CustomObject>
    <label>Payment Mode</label>
    <nameField>
        <label>Payment Mode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Mode</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment_Retry__c.object
<CustomObject>
    <fields>
        <fullName>CL_Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CL Contract</label>
        <referenceTo>loan__Loan_Account__c</referenceTo>
        <relationshipLabel>Payment Retry</relationshipLabel>
        <relationshipName>Payment_Retry</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Debit_amount__c</fullName>
        <label>Debit amount</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Retry_Attempted_On__c</fullName>
        <label>Retry Attempted On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Retry_Attempted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Retry Attempted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <label>Payment Retry</label>
    <nameField>
        <label>Payment Retry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Retry</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LoanPaymentTransactionRetryJob.cls
public class LoanPaymentTransactionRetryJob implements Database.Batchable<sObject>, Schedulable {
    private String query;
    private List<loan__Loan_Payment_Transaction__c> loanPayments;
    private loan__Payment_Mode__c pMode;
    private List<loan__Batch_Process_Log__c> blogs;
    private loan.GlobalLoanUtilFacade facade;
    private Date sysDate;
    
    /* Constructor */
    public LoanPaymentTransactionRetryJob() {
        
        facade = new loan.GlobalLoanUtilFacade();
        sysDate = facade.getCurrentSystemDate();
        
        this.query = ProcessJobQueryUtil.getRetryJobQuery(sysDate);
        
        loanPayments = new List<loan__Loan_Payment_Transaction__c>();
        bLogs = new List<loan__Batch_Process_Log__c>();
        
        pMode = [Select Id,Name from loan__Payment_Mode__c Where Name = 'ACH' limit 1];
    
    }
    
    public void execute(SchedulableContext sc) {
        
    }
        
    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bc, List<sObject> scope) {
        
        List<Payment_Retry__c> retryTxns = (List<Payment_Retry__c>) scope;
        loan__Loan_Payment_Transaction__c lptToCreate;
        
        Savepoint sp = Database.setSavepoint();
        try{
        
            for(Payment_Retry__c retry : retryTxns) {
                lptToCreate = getNewLoanPayment(retry);
                loanPayments.add(lptToCreate);
                
                retry.Retry_Attempted__c = true;
                retry.Retry_Attempted_On__c = sysDate;
                
            }
            
            //insert loan payments
            insert loanPayments;
            
            //update retry attempted flag on retry order
            update retryTxns;
        }catch(Exception e) {
            Database.rollback(sp);
            loan__Batch_Process_Log__c errorLog = new loan__Batch_Process_Log__c();
            errorLog.loan__Message__c = 'Error : LoanPaymentTransactionRetryJob: '+e.getMessage()+' from line '+e.getLineNumber();
            errorLog.loan__Date__c = Date.newInstance(System.now().year(),System.now().month(),System.now().day());
            
            bLogs.add(errorLog);
            insert bLogs;
        }
    }
    @TestVisible 
    private loan__Loan_Payment_Transaction__c getNewLoanPayment(Payment_Retry__c rec) {
        loan__Loan_Payment_Transaction__c retVal = new loan__Loan_Payment_Transaction__c();
        
        retVal.loan__Transaction_Date__c = rec.Transaction_Date__c;
        retVal.loan__Transaction_Amount__c = rec.Debit_Amount__c;
        retVal.loan__Payment_Mode__c = pMode.Id;
        retVal.loan__Loan_Account__c = rec.CL_Contract__c;
        retVal.loan__Receipt_Date__c = rec.Transaction_Date__c;
        retVal.Payment_Type__c = 'Retry';
        
        return retVal;
    }
    
    
    public void finish(Database.BatchableContext bc){
    
    }
}